### ISSUE TITLE
xCode 10.2/Swift5.0 Failed to generate documentation

### ISSUE THREAD

**Issue by alex-fos** [realm/jazzy#1059]
jazzy: 0.9.5
xCode: Version 10.2 (10E125)

Steps:
1. Create the new single-view iOS app
2. In terminal, run 'jazzy'

**Actual results:**
dhcp201-33-83:test alilyin$ jazzy
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/v1/6qjc7r6d3z36r1s2mvwms91w0000gn/T/xcodebuild-564ACA5A-F9DB-4191-A2EF-A18C7E8CD303.log
Failed to generate documentation
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/bin/sourcekitten ["doc", "--"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/v1/6qjc7r6d3z36r1s2mvwms91w0000gn/T/xcodebuild-564ACA5A-F9DB-4191-A2EF-A18C7E8CD303.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.5/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'

**xcodebuild-564ACA5A-F9DB-4191-A2EF-A18C7E8CD303.log Content:**

Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO

note: Using new build system

** CLEAN SUCCEEDED **

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target 'test')

** BUILD FAILED **

**Note: Jazzy 0.9.5 works fine with xCode 10.01 (10B61)**

**Comment by alex-fos** [comment]
Duplicate of https://github.com/realm/jazzy/issues/1057
