### ISSUE TITLE
sourcekitten runtime error

### ISSUE THREAD

**Issue by usinuniverse** [realm/jazzy#1097]
```
jazzy --min-acl internal
Running xcodebuild
Parsing AppDelegate.swift (1/173)
Parsing AJLCategoryViewController.swift (2/173)
Parsing AJLCategoryCollectionViewCell.swift (3/173)
Parsing AJLCategoryHeaderView.swift (4/173)
Parsing AJLConstants.swift (5/173)
Parsing AJLDateExtension.swift (6/173)
Parsing AJLHTTPCookieStorageExtension.swift (7/173)
Parsing AJLInt32Extension.swift (8/173)
Parsing AJLIntExtension.swift (9/173)
Parsing AJLStringExtension.swift (10/173)
Parsing AJLUIColorExtension.swift (11/173)
Parsing AJLUIFontExtension.swift (12/173)
Parsing AJLUIImageExtension.swift (13/173)
Parsing AJLUIImageViewExtension.swift (14/173)
Parsing AJLUIViewControllerExtension.swift (15/173)
Parsing AJLDeviceManager.swift (16/173)
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/sourcekitten ["doc", "--"] (RuntimeError)

Running xcodebuild

Parsing AppDelegate.swift (1/173)

Parsing AJLCategoryViewController.swift (2/173)

Parsing AJLCategoryCollectionViewCell.swift (3/173)

Parsing AJLCategoryHeaderView.swift (4/173)

Parsing AJLConstants.swift (5/173)

Parsing AJLDateExtension.swift (6/173)

Parsing AJLHTTPCookieStorageExtension.swift (7/173)

Parsing AJLInt32Extension.swift (8/173)

Parsing AJLIntExtension.swift (9/173)

Parsing AJLStringExtension.swift (10/173)

Parsing AJLUIColorExtension.swift (11/173)

Parsing AJLUIFontExtension.swift (12/173)

Parsing AJLUIImageExtension.swift (13/173)

Parsing AJLUIImageViewExtension.swift (14/173)

Parsing AJLUIViewControllerExtension.swift (15/173)

Parsing AJLDeviceManager.swift (16/173)
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.10.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
```

I am having a problem.
I am getting a runtime error.
I do not understand why this happens.
Do you have any doubts?

**Comment by johnfairh** [comment]
Maybe #1083 -- check for `///` comments in the middle of functions in `AJLDeviceManager.swift`.

**Comment by usinuniverse** [comment]
@johnfairh I'm check all functions in `AJLDeviceManager.swift`. But I couldn't find triple slashes.

**Comment by usinuniverse** [comment]
@johnfairh Couldn't I use a triple slash not only in fuction but also outside?

**Comment by johnfairh** [comment]
The 1083 bug needs there to be a doc comment on something that is not a declaration.  (actually it could be `/** */`, not just `///`)

If you are sure that there are none of these then it sounds like your project has found a new problem.  If you cannot share the project then I'm afraid the only way to find the part of the file that is causing the crash is to disable parts until the problem goes away so we can make a recreate.

**Comment by usinuniverse** [comment]
I understand. I'd like to try it right away, but the source code is on the company computer and I'm off work. I'll try again as soon as I get to work, and if it doesn't work, I'll share the source code with you.

**Comment by usinuniverse** [comment]
I've removed the triple slash from other source code with the same error. The result was good. Thank.
