### ISSUE TITLE
Error while running jazzy on Ubuntu 18.04 with Swift Package Manager

### ISSUE THREAD

**Issue by param087** [realm/jazzy#1105]
```
$ jazzy
/var/lib/gems/2.5.0/gems/jazzy-0.11.0/bin/sourcekitten: 1: /var/lib/gems/2.5.0/gems/jazzy-0.11.0/bin/sourcekitten: Syntax error: "(" unexpected
Traceback (most recent call last):
	7: from /usr/local/bin/jazzy:23:in `<main>'
	6: from /usr/local/bin/jazzy:23:in `load'
	5: from /var/lib/gems/2.5.0/gems/jazzy-0.11.0/bin/jazzy:15:in `<top (required)>'
	4: from /var/lib/gems/2.5.0/gems/jazzy-0.11.0/lib/jazzy/doc_builder.rb:62:in `build'
	3: from /var/lib/gems/2.5.0/gems/jazzy-0.11.0/lib/jazzy/doc_builder.rb:62:in `chdir'
	2: from /var/lib/gems/2.5.0/gems/jazzy-0.11.0/lib/jazzy/doc_builder.rb:64:in `block in build'
	1: from /var/lib/gems/2.5.0/gems/jazzy-0.11.0/lib/jazzy/sourcekitten.rb:238:in `run_sourcekitten'
/var/lib/gems/2.5.0/gems/jazzy-0.11.0/lib/jazzy/executable.rb:36:in `execute_command': /var/lib/gems/2.5.0/gems/jazzy-0.11.0/bin/sourcekitten ["doc", "--spm", "--"] (RuntimeError)

/var/lib/gems/2.5.0/gems/jazzy-0.11.0/bin/sourcekitten: 1: /var/lib/gems/2.5.0/gems/jazzy-0.11.0/bin/sourcekitten: Syntax error: "(" unexpected

```

**Comment by johnfairh** [comment]
Jazzy's primary target is still macOS: the `sourcekitten` binary in the jazzy gem is for macOS.  For Linux you will need to install sourcekitten separately, see [this comment and its references](https://github.com/realm/jazzy/issues/495#issuecomment-383335707).

Reviewing our readme this is not at all clear now we mention SwiftPM up-front so I will fix that.

**Comment by param087** [comment]
Thanks.
