### ISSUE TITLE
jazzy unable to run

### ISSUE THREAD

**Issue by twodayslate** [realm/jazzy#1154]
I get the following error after a `sudo gem install jazzy`:
```bash
% jazzy
﻿Traceback (most recent call last):
	12: from /Users/user/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	11: from /Users/user/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	10: from /Users/user/.rvm/rubies/ruby-2.6.3/bin/jazzy:23:in `<main>'
	 9: from /Users/user/.rvm/rubies/ruby-2.6.3/bin/jazzy:23:in `load'
	 8: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/jazzy-0.13.1/bin/jazzy:13:in `<top (required)>'
	 7: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/jazzy-0.13.1/lib/jazzy.rb:2:in `<top (required)>'
	 4: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/jazzy-0.13.1/lib/jazzy/doc_builder.rb:4:in `<top (required)>'
	 1: from /Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sassc (LoadError)
```

On macOS 10.15.2

```bash
% uname -a
Darwin MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```

``` bash
% sudo gem list
activesupport (4.2.11.1)
algoliasearch (1.27.1)
atomos (0.1.3)
bigdecimal (default: 1.4.1)
bundler (default: 1.17.3)
bundler-unload (1.0.2)
CFPropertyList (3.0.1)
claide (1.0.3)
cmath (default: 1.0.0)
cocoapods (1.8.4)
cocoapods-core (1.8.4)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.3.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.4.1)
cocoapods-try (1.1.0)
colored2 (3.1.2)
concurrent-ruby (1.1.5)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
escape (0.0.4)
etc (default: 1.0.1)
executable-hooks (1.6.0)
fcntl (default: 1.0.0)
ffi (1.11.3)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
fourflusher (2.3.1)
fuzzy_match (2.0.4)
gdbm (default: 2.0.0)
gem-wrappers (1.4.0)
gh_inspector (1.1.3)
httpclient (2.8.3)
i18n (0.9.5)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jazzy (0.13.1)
json (default: 2.1.0)
liferaft (0.0.6)
logger (default: 1.3.0)
matrix (default: 0.1.0)
minitest (5.11.3)
molinillo (0.6.6)
mustache (1.1.0)
mutex_m (default: 0.1.0)
nanaimo (0.2.6)
nap (1.1.0)
net-telnet (0.2.0)
netrc (0.11.0)
open4 (1.3.4)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (12.3.2)
rdoc (default: 6.1.0)
redcarpet (3.5.0)
rexml (default: 3.1.9)
rouge (3.13.0)
rss (default: 0.2.7)
ruby-macho (1.4.0)
rubygems-bundler (1.4.5)
rvm (1.11.3.9)
sassc (2.2.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
sqlite3 (1.4.1)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (1.2.5)
webrick (default: 1.4.2)
xcinvoke (0.3.0)
xcodeproj (1.13.0)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

**Comment by johnfairh** [comment]
Caveat: I'm wary of the `sudo`s above especially in conjunction with rvm -- assume you know what is going on there.

There is a bunch of discussion of this (LoadError on 2.2) in sass/sassc-ruby#146.  People have suggested various problems & remedies but there is no real agreement AFAICT on what the problems are and why it only affects some people (I've installed this gem a lot on loads of varieties of system and not seen it).  Summary things to try:
*  Downgrade the sassc gem to 2.1.
*  Reinstall the sassc gem with a C flag disabled:
    ```shell 
    gem uninstall sassc
    gem install sassc -- --disable-march-tune-native
    ```
    (Nobody can explain why this affects non-cross-compile scenarios but various macOS users claim it helped them so.. worth a shot...)
* Make sure you don't have a bad version of `strip` from Carthage or other non-Xcode build tools ahead of the Xcode ones, then uninstall & reinstall it.

**Comment by twodayslate** [comment]
Thanks for the link and information. Still didn't work for me tho :( I did get a different error tho. 

```bash
% jazzy
Traceback (most recent call last):
	17: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	16: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	15: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/bin/jazzy:23:in `<main>'
	14: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/bin/jazzy:23:in `load'
	13: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/gems/jazzy-0.13.1/bin/jazzy:13:in `<top (required)>'
	12: from /Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/gems/jazzy-0.13.1/lib/jazzy.rb:2:in `<top (required)>'
	 9: from /Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/gems/jazzy-0.13.1/lib/jazzy/doc_builder.rb:4:in `<top (required)>'
	 6: from /Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/gems/sassc-2.1.0/lib/sassc.rb:31:in `<top (required)>'
	 3: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/gems/sassc-2.1.0/lib/sassc.rb:31:in `require_relative'
	 2: from /Users/zrgorak/.rvm/gems/ruby-2.6.3/gems/sassc-2.1.0/lib/sassc/native.rb:3:in `<top (required)>'
	 1: from /Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/zrgorak/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffi (LoadError)
```

```bash
% which strip && strip
/usr/bin/strip
fatal error: /Applications/Xcode_11_3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: no files specified
```
I guess the Xcode version of strip doesn't have --version, even tho it is in the man page. 

```
activesupport (4.2.11.1)
algoliasearch (1.27.1)
atomos (0.1.3)
bigdecimal (default: 1.4.1)
bundler (default: 1.17.3)
bundler-unload (1.0.2)
CFPropertyList (3.0.1)
claide (1.0.3)
cmath (default: 1.0.0)
cocoapods (1.8.4)
cocoapods-core (1.8.4)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.3.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.4.1)
cocoapods-try (1.1.0)
colored2 (3.1.2)
concurrent-ruby (1.1.5)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
escape (0.0.4)
etc (default: 1.0.1)
executable-hooks (1.6.0)
fcntl (default: 1.0.0)
ffi (1.11.3)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
fourflusher (2.3.1)
fuzzy_match (2.0.4)
gdbm (default: 2.0.0)
gem-wrappers (1.4.0)
gh_inspector (1.1.3)
httpclient (2.8.3)
i18n (0.9.5)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
jazzy (0.13.1)
json (default: 2.1.0)
liferaft (0.0.6)
logger (default: 1.3.0)
matrix (default: 0.1.0)
minitest (5.11.3)
molinillo (0.6.6)
mustache (1.1.0)
mutex_m (default: 0.1.0)
nanaimo (0.2.6)
nap (1.1.0)
net-telnet (0.2.0)
netrc (0.11.0)
open4 (1.3.4)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (12.3.2)
rdoc (default: 6.1.0)
redcarpet (3.5.0)
rexml (default: 3.1.9)
rouge (3.13.0)
rss (default: 0.2.7)
ruby-macho (1.4.0)
rubygems-bundler (1.4.5)
rvm (1.11.3.9)
sassc (2.1.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
sqlite3 (1.4.1)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thread_safe (0.3.6)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (1.2.5)
webrick (default: 1.4.2)
xcinvoke (0.3.0)
xcodeproj (1.13.0)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

It was fixed with
```bash
% gem install ffi --platform=ruby 
```

**Comment by johnfairh** [comment]
Ok; do you mean you are all good now or just back to broken as in OP?

**Comment by twodayslate** [comment]
jazzy runs now :)

However I get stuck at building site. Probably not related to this issue so this can be closed.

**Comment by johnfairh** [comment]
🎉
