### ISSUE TITLE
Jazzy can't find pod modulemap 

### ISSUE THREAD

**Issue by fprosper** [realm/jazzy#1182]
Hi I am running jazzy version 0.13.2, using Xcode 11.4 for a swift project.
I have some pods in my project, one of them is Alamofire.

I am running jazzy with the following arguments:
```
@jazzy \
        --min-acl internal \
        --no-hide-documentation-coverage \
        --theme fullwidth \
        --output ./docs \
	--documentation=./*.md
	@rm -rf ./build
```

This is the error I can see in the log:

```
<unknown>:0: error: module map file '/Users/fabrizio/Developer/Projects/FCA_LeasysApp_iOS/build/Release-iphoneos/Alamofire/Alamofire.modulemap' not found
<unknown>:0: error: missing required module 'SwiftShims'

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

The module map files are instead in  the Pods directories:

```
./Pods/Target Support Files/Alamofire/Alamofire.modulemap
./Pods/Headers/Public/Alamofire/Alamofire.modulemap
```

What did I do wrong?

**Comment by johnfairh** [comment]
Jazzy is running `xcodebuild` and getting that error.  Try running `xcodebuild` yourself -- it should fail, then you can figure out what arguments it needs to build your target module cleanly and pass those to jazzy with `--build-tool-arguments`.

**Comment by fprosper** [comment]
Thank you, you were right. Now I have figured out the command to make` xcodebuild` work, it is:

`xcodebuild -workspace leasys_ios.xcworkspace -scheme leasys_ios`

but I can't figure out how to use it with `--build-tool-arguments`, as the following is not working:

```
@jazzy \
        --min-acl internal \
        --no-hide-documentation-coverage \
        --theme fullwidth \
        --output ./docs \
        --build-tool-arguments -workspace,leasys_ios.xcworkspace -scheme,leasys_ios \
	--documentation=./*.md 
	@rm -rf ./build
```

```
Traceback (most recent call last):
	6: from /usr/local/bin/jazzy:23:in `<main>'
	5: from /usr/local/bin/jazzy:23:in `load'
	4: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.2/bin/jazzy:15:in `<top (required)>'
	3: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:70:in `build'
	2: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:70:in `map'
	1: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:70:in `read'
/Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:70:in `read': No such file or directory @ rb_sysopen - /Users/fabrizio/Developer/Projects/FCA_LeasysApp_iOS/cheme (Errno::ENOENT)
make: *** [documentation] Error 1
```

**Comment by fprosper** [comment]
Ok managed with:

`        --xcodebuild-arguments -scheme,leasys_ios,-workspace,leasys_ios.xcworkspace `

Thank you very much for your help!
