### ISSUE TITLE
Using Jazzy with Swift Package Manager

### ISSUE THREAD

**Issue by jtbergman** [realm/jazzy#1207]
### Description
I am trying to use Jazzy with a Swift framework in Xcode version 11.5. If I remove all the third-party dependencies from the framework and run `jazzy` everything builds fine. 

### Issue
I am trying to use `RealmSwift` which I am installing using Swift Package Manager. When I run Jazzy with Realm added, I get:
```
Running xcodebuild
Could not successfully run `xcodebuild`.
Please check the build arguments.
Saved `xcodebuild` log file: /var/folders/h6/jszpzp7d77v20xlpgt3md6br0t77yv/T/xcodebuild-2AAD42BD-2B94-46A6-AE6A-1740F29931EF.log
Failed to generate documentation
Traceback (most recent call last):
	7: from /usr/local/bin/jazzy:23:in `<main>'
	6: from /usr/local/bin/jazzy:23:in `load'
	5: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.4/bin/jazzy:15:in `<top (required)>'
	4: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.4/lib/jazzy/doc_builder.rb:76:in `build'
	3: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.4/lib/jazzy/doc_builder.rb:76:in `chdir'
	2: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.4/lib/jazzy/doc_builder.rb:78:in `block in build'
	1: from /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.4/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
/Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.4/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.6.0/gems/jazzy-0.13.4/bin/sourcekitten ["doc", "--"] (RuntimeError)

Running xcodebuild

Could not successfully run `xcodebuild`.

Please check the build arguments.

Saved `xcodebuild` log file: /var/folders/h6/jszpzp7d77v20xlpgt3md6br0t77yv/T/xcodebuild-2AAD42BD-2B94-46A6-AE6A-1740F29931EF.log

Failed to generate documentation
```

The log file includes the following 
```
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild

Resolve Package Graph

Resolved source packages:
  RealmCore: https://github.com/realm/realm-core @ 6.0.6
  Realm: https://github.com/realm/realm-cocoa @ 5.1.0


note: Using new build system
note: Planning build
note: Constructing build description

... some stuff ... 

fatal error: module map file '/Users/user/Library/Developer/Xcode/DerivedData/ProjectName-bweysdoppfcupaetdvqoxpwqmhgu/SourcePackages/checkouts/realm-cocoa/build/GeneratedModuleMaps/iphoneos/RealmCore.modulemap' not found
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'Realm' from project 'Realm')

... same error multiple times ... 

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/user/Library/Developer/Xcode/DerivedData/ProjectName-bweysdoppfcupaetdvqoxpwqmhgu/SourcePackages/checkouts/realm-cocoa/build/Realm.build/Release-iphoneos/Realm.build/Objects-normal/arm64/binding_callback_thread_observer.o /Users/user/Library/Developer/Xcode/DerivedData/ProjectName-bweysdoppfcupaetdvqoxpwqmhgu/SourcePackages/checkouts/realm-cocoa/Realm/ObjectStore/src/binding_callback_thread_observer.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by johnfairh** [comment]
The output is saying that `xcodebuild` failed.  You'll need to figure out what arguments it needs to make your Xcode project/workspace file build and pass those to jazzy using `--build-tool-arguments`.

**Comment by fishercraigj** [comment]
what package did you download to even get Jazzy?  I can't find it when I search within Xcode SPM searches.

**Comment by davegomez** [comment]
I'm trying to install jazzy in my project using Swift Package Manager and I'm getting the following error:

```sh
$ swift build
Updating https://github.com/apple/swift-crypto.git
Updating https://github.com/realm/jazzy.git
https://github.com/realm/jazzy.git @ 0.13.5: error: https://github.com/realm/jazzy.git has no Package.swift manifest for version 0.13.5
```

It would be nice to include documentation on how to install jazzy using Swift Package Manager if there is something special you need to do in order to be able to use the library.

**Comment by johnfairh** [comment]
Closing, answered; @davegomez: Jazzy is a Ruby program that you can install with `gem install` - see the readme.
