### ISSUE TITLE
Can't install jazzy

### ISSUE THREAD

**Issue by Stephan-AppFabrik** [realm/jazzy#1240]
Hi, I got a problem with installing jazzy on my Mac. Thanks for your help.

I use these versions:
- Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
- Xcode 12.4
Build version 12D4e
- ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
- Xcode development tools are already installed
- Mac: 10.15.7

```
C02D31KMMD6M:~ stezel$ sudo gem install jazzy
Building native extensions. This could take a while...
ERROR:  Error installing jazzy:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20210311-4673-1d1oo3o.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:672:in `try_ldflags'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1832:in `pkg_config'
	from extconf.rb:9:in `system_libffi_usable?'
	from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/ffi-1.15.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.0 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/ffi-1.15.0/gem_make.out

```

**Comment by johnfairh** [comment]
Probably see #1229 --- Xcode 12 and macOS 10 aren't a matching pair.

**Comment by Stephan-AppFabrik** [comment]
> Probably see #1229 --- Xcode 12 and macOS 10 aren't a matching pair.
Thanks at first :)
At #1229 you said: "just to be clear you don't need to downgrade anything, just grab Xcode 11 and select it while installing jazzy."

Might you please tell me exactly what I have to do? I installed Xcode 11.7. , but I can't find it on my Macbook and also I have no idea how I can select it for installing jazzy.

**Comment by Stephan-AppFabrik** [comment]
Worked now as you explained in #1229 thanks a lot!

**Comment by Stephan-AppFabrik** [comment]
For future people:
- Downloaded Xcode 11.7 from https://developer.apple.com/download/more/
- Add Xcode 11.7 to Application folder
- (Optional: Rename them, that you know which version is which one)
- sudo gem install jazzy -n /usr/local/bin      worked for me
- if not, change the selected Xcode version: $ sudo xcode-select -s /Applications/Xcode11.7.app/Contents/Developer
-  sudo gem install jazzy -n /usr/local/bin   should worked now
- Select new current Xcode version again: $ sudo xcode-select -s /Applications/Xcode12.4.app/Contents/Developer
- That's how it worked for me
