### ISSUE TITLE
jazzy_markdown.rb:74:in `escapeHTML': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by Wei18** [realm/jazzy#1270]
```
Traceback (most recent call last):
	20: from /Users/zw/.gem/bin//jazzy:23:in `<main>'
	19: from /Users/zw/.gem/bin//jazzy:23:in `load'
	18: from /Users/zw/.gem/gems/jazzy-0.13.7/bin/jazzy:15:in `<top (required)>'
	17: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/doc_builder.rb:85:in `build'
	16: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/doc_builder.rb:153:in `build_docs_for_sourcekitten_output'
	15: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:1005:in `parse'
	14: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:530:in `make_source_declarations'
	13: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:530:in `each'
	12: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:532:in `block in make_source_declarations'
	11: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:530:in `make_source_declarations'
	10: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:530:in `each'
	 9: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:586:in `block in make_source_declarations'
	 8: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:519:in `make_substructure'
	 7: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:530:in `make_source_declarations'
	 6: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:530:in `each'
	 5: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:585:in `block in make_source_declarations'
	 4: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/sourcekitten.rb:369:in `make_doc_info'
	 3: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/jazzy_markdown.rb:231:in `render'
	 2: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/jazzy_markdown.rb:231:in `render'
	 1: from /Users/zw/.gem/gems/jazzy-0.13.7/lib/jazzy/jazzy_markdown.rb:74:in `codespan'
```

**Comment by Wei18** [comment]
The ` ` cause the issue.
```
\\\ ` `(Space) also.
```

**Comment by johnfairh** [comment]
Thanks - looks like a bug in the KaTeX support, unexpectedly getting a `nil` from redcarpet...
