### ISSUE TITLE
The installation of jazzy through gem does not work (OSX 13.4.1 / XCode 14.3.1)

### ISSUE THREAD

**Issue by LairdTurner** [realm/jazzy#1357]
I wanted to install jazzy using the gem install jazzy command. The installation seems to run but I can not start jazzy by entering the command jazzy in the terminal. Jazzy is created in the binary directory of gem. When I start this then I get the following error message:

./jazzy 
Running swift build
Build failed, saved `swift build` log file: /var/folders/f4/vv9g2p2n0ng8mvzc0qryc6km0000gn/T/swift-build-585C25A9-B9FF-41AE-B2E5-E7FBCA272F94.log
Error: Failed to generate documentation
/usr/local/lib/ruby/gems/3.2.0/gems/jazzy-0.14.3/lib/jazzy/executable.rb:39:in `execute_command': /usr/local/lib/ruby/gems/3.2.0/gems/jazzy-0.14.3/bin/sourcekitten ["doc", "--spm", "--"] (RuntimeError)

Running swift build

Build failed, saved `swift build` log file: /var/folders/f4/vv9g2p2n0ng8mvzc0qryc6km0000gn/T/swift-build-585C25A9-B9FF-41AE-B2E5-E7FBCA272F94.log

Error: Failed to generate documentation

	from /usr/local/lib/ruby/gems/3.2.0/gems/jazzy-0.14.3/lib/jazzy/sourcekitten.rb:269:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/3.2.0/gems/jazzy-0.14.3/lib/jazzy/doc_builder.rb:82:in `block in build'
	from /usr/local/lib/ruby/gems/3.2.0/gems/jazzy-0.14.3/lib/jazzy/doc_builder.rb:80:in `chdir'
	from /usr/local/lib/ruby/gems/3.2.0/gems/jazzy-0.14.3/lib/jazzy/doc_builder.rb:80:in `build'
	from /usr/local/lib/ruby/gems/3.2.0/gems/jazzy-0.14.3/bin/jazzy:16:in `<top (required)>'
	from ./jazzy:25:in `load'
	from ./jazzy:25:in `<main>'

I'm running XCode 14.3.1

Many greetings

      René

**Comment by johnfairh** [comment]
Jazzy is telling you it cannot build a swift project and to read the log file it mentions.

I can't help you with your Ruby installation - from your pastes it looks like there should be a `/usr/local/bin/jazzy`
