### ISSUE TITLE
Runtime error in running jazzy: undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

### ISSUE THREAD

**Issue by zorgiepoo** [realm/jazzy#1370]
My GitHub actions CI which uses jazzy is now running into a runtime error when running jazzy:

```
jazzy --author "Sparkle Project" --objc --umbrella-header Sparkle/Sparkle.h --framework-root . --readme Documentation/API_README.markdown --theme jony --output Documentation/html
/Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:8:in `<top (required)>'
	from <internal:/Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/cocoapods-1.13.0/lib/cocoapods.rb:9:in `<top (required)>'
	from <internal:/Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/podspec_documenter.rb:42:in `create_podspec'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:301:in `block in <class:Config>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:37:in `instance_exec'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:37:in `set'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:42:in `set_to_default'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:495:in `block in initialize'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:494:in `each'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:494:in `initialize'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:505:in `new'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/lib/jazzy/config.rb:505:in `parse!'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/lib/ruby/gems/3.2.0/gems/jazzy-0.14.4/bin/jazzy:16:in `<top (required)>'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/bin/jazzy:25:in `load'
	from /Users/runner/hostedtoolcache/Ruby/3.2.2/x64/bin/jazzy:25:in `<main>'
```

The GitHub action just sets up Ruby and jazzy:

```
    steps:
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: "Set up jazzy"
        run: |
          gem install jazzy
```

From some online searching I think this is related to a recent change in ActiveSupport:
https://github.com/CocoaPods/CocoaPods/issues/12081
https://github.com/rails/rails/issues/49495

One particular note in the latter thread I see is:
> The error seems to happen when not requiring active_support before requiring the specific functionality. According to the documentation https://guides.rubyonrails.org/active_support_core_extensions.html , you're always expected to require 'active_support' first

I see for instance jazzy does `require 'active_support/inflector'`  but does not `require 'active_support'` first (see also cocoapod's fix in https://github.com/CocoaPods/CocoaPods/pull/12082/). Maybe that is one of the issues here. Not sure if this project also depends in cocoapods or not and needs a fix from them.

**Comment by johnfairh** [comment]
Thanks for this.

As far as I can tell this is the cocoapods issue -- from the stacktrace it is using cocoapods 1.13.0 with activesupport 7.1.1.
So the real fix is to wait for cocoapods to do a new release including the fix.

You're right that jazzy does apparently break the activesupport rules but that particular require doesn't seem to cause a problem -- I will fix it though in case of future breakage.

You can probably fix your CI by manually uninstalling activesupport and then installing 7.0.8.
```shell
gem uninstall activesupport -v 7.1.1
gem install activesupport -v 7.0.8
```

**Comment by johnfairh** [comment]
Will keep this issue open for the cocoapods fix - if they don't get a release out this week then I guess I could do a jazzy release to cap activesupport.

**Comment by johnfairh** [comment]
Cocoapods gem 1.14.0 is out with the activesupport fix, everything seems to work OK with latest gems.
