### ISSUE TITLE
After updating to v0.0.20 getting error even with -v option 

### ISSUE THREAD

**Issue by juangamnik** [realm/jazzy#139]
I updated to v0.0.20 and now I get the following error (independent of using no command-line option or `-c` or `-v`):
```bash
$ jazzy -v
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require': dlopen(/usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0/sqlite3-1.3.10/sqlite3/sqlite3_native.bundle, 9): Library not loaded: /usr/local/lib/libruby.2.1.0.dylib (LoadError)
  Referenced from: /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0/sqlite3-1.3.10/sqlite3/sqlite3_native.bundle
  Reason: image not found - /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0/sqlite3-1.3.10/sqlite3/sqlite3_native.bundle
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.10/lib/sqlite3.rb:6:in `rescue in <top (required)>'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/sqlite3-1.3.10/lib/sqlite3.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.0.19/lib/jazzy/docset_builder.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.0.19/lib/jazzy/doc_builder.rb:9:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.0.19/lib/jazzy.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/jazzy-0.0.19/bin/jazzy:13:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

I tried to reinstall all my gems, but the issue remains. Any ideas? Is my environment (ruby installation or sqlite installation) broken?

**Comment by juangamnik** [comment]
For your information:
```bash
$ gem list jazzy

*** LOCAL GEMS ***

jazzy (0.0.20)
```

**Comment by segiddins** [comment]
This seems to me to be an issue with either your ruby install or your SQLite install.

**Comment by juangamnik** [comment]
Hmm. I tried to uninstall ruby with homebrew and use the apple version again. I uninstalled and installed jazzy again. In the executable script it still uses `#!/usr/local/Cellar/ruby/2.1.5/bin/ruby` which did not work anymore as I deinstalled this ruby-version. I changed the header to `#!/usr/bin/ruby` and now it works again.
