### ISSUE TITLE
Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed

### ISSUE THREAD

**Issue by dabrahams** [realm/jazzy#1391]
Ever since we upgraded to Swift 5.10, we're seeing [this](https://github.com/hylo-lang/hylo/actions/runs/9143137716/job/25139449168#step:10:46) in our CI.  The CI [installs jazzy and Swift 5.10](https://github.com/hylo-lang/hylo/blob/6f57cb5442dc982610ff6e27e1266d24e944cc7c/.github/workflows/doc-extraction.yml#L41-L48).  Do we need to update Xcode as well?

```
Using config file /Users/runner/work/hylo/hylo/.jazzy.yml
Running swift build
Parsing FullPathInFatalErrors.swift (1/2)
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
/usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/lib/jazzy/executable.rb:39:in `execute_command': /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/bin/sourcekitten ["doc", "--spm", "--module-name", "hc", "--"] (RuntimeError)

Running swift build

Parsing FullPathInFatalErrors.swift (1/2)

SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/lib/jazzy/sourcekitten.rb:2[29](https://github.com/hylo-lang/hylo/actions/runs/9137274908/job/25127065260#step:10:30):in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/lib/jazzy/doc_builder.rb:83:in `block (2 levels) in build'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/lib/jazzy/doc_builder.rb:81:in `chdir'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/lib/jazzy/doc_builder.rb:81:in `block in build'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/lib/jazzy/doc_builder.rb:71:in `map'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/lib/jazzy/doc_builder.rb:71:in `build'
	from /usr/local/lib/ruby/gems/3.0.0/gems/jazzy-0.15.0/bin/jazzy:16:in `<top (required)>'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jazzy:25:in `load'
	from /usr/local/lib/ruby/gems/3.0.0/bin/jazzy:25:in `<main>'
```

**Comment by johnfairh** [comment]
It looks like the macOS swift.org toolchains don't include `sourcekitdInProc.framework`.  Maybe there is some 'include all the stuff' variant somewhere, but doesn't seem to be a new problem, found [this](https://github.com/realm/SwiftLint/issues/5325).

You're right that moving CI to macOS 14 / Xcode 15.3 with the full-fat toolchain would fix this, big hammer though.

**Comment by dabrahams** [comment]
Not a problem for my project; thanks. Worked on macOS-12 strangely.
