### ISSUE TITLE
Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed

### ISSUE THREAD

**Issue by dabrahams** [realm/jazzy#1407]
For about the last 2 months, my Jazzy CI jobs are failing with:

```
Using config file /Users/runner/work/hylo/hylo/.jazzy.yml
Running swift build
Parsing FullPathInFatalErrors.swift (1/2)
SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
/opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/lib/jazzy/executable.rb:39:in `execute_command': /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/bin/sourcekitten ["doc", "--spm", "--module-name", "hc", "--"] (RuntimeError)

Running swift build

Parsing FullPathInFatalErrors.swift (1/2)

SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/lib/jazzy/sourcekitten.rb:2[29](https://github.com/hylo-lang/hylo/actions/runs/11767142239/job/32775492599#step:10:30):in `run_sourcekitten'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/lib/jazzy/doc_builder.rb:83:in `block (2 levels) in build'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/lib/jazzy/doc_builder.rb:81:in `chdir'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/lib/jazzy/doc_builder.rb:81:in `block in build'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/lib/jazzy/doc_builder.rb:71:in `map'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/lib/jazzy/doc_builder.rb:71:in `build'
	from /opt/homebrew/lib/ruby/gems/3.0.0/gems/jazzy-0.15.3/bin/jazzy:16:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jazzy:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.0.0/bin/jazzy:25:in `<main>'
Error: Process completed with exit code 1.
```

Ideas?

**Comment by johnfairh** [comment]
I guess still https://github.com/realm/jazzy/issues/1391#issuecomment-2131210345 - the swift.org toolchain installed in CI does not include the right dylibs.

**Comment by dabrahams** [comment]
Yes, upgrading my GH runner to `macos-15` fixes the problem, thanks.
