### ISSUE TITLE
sourcekitten.rb exception when using compilation flags

### ISSUE THREAD

**Issue by Reflejo** [realm/jazzy#142]
While trying to build the doc site, jazzy crashes on an example like the following:

```swift
struct Test {
    #if DEBUG
    static let TestA = true
    #else
    static let TestB = false
    #endif
}
```

with:

```
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:41:in `+': no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:41:in `block in make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:32:in `make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:37:in `block in make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:32:in `make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:37:in `block in make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:32:in `make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/sourcekitten.rb:181:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/doc_builder.rb:102:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.0.20/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```

The reason being that "key.usr" is empty when evaluating "TestA" and therefore doc.usr is empty too, breaking:

```ruby
doc.url = parents.join('/') + '.html#/' + doc.usr
```

**Comment by jpsim** [comment]
Thanks for reporting this, @Reflejo. This is now fixed.
