### ISSUE TITLE
Jazzy Fail on parsing

### ISSUE THREAD

**Issue by jeeftor** [realm/jazzy#200]
My Jazzy has failed, but I'm not sure how to diagnose what is causing the issue.  My code builds fine in Xcode.  Any suggestions?

```
Running xcodebuild -dry-run
Parsing TestingExtensions.swift (1/8)
Parsing FilePlayer.swift (2/8)
Parsing ConnectionManager.swift (3/8)
Parsing ParsedMessages.swift (4/8)
Parsing MessageFactory.swift (5/8)
Parsing DataManager.swift (6/8)
Parsing NotificationExtensions.swift (7/8)
Parsing DelegateProtocols.swift (8/8)
building site
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:41:in `+': no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:41:in `block in make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:32:in `make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:37:in `block in make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:32:in `make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:37:in `block in make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:32:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:32:in `make_doc_urls'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/sourcekitten.rb:194:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/doc_builder.rb:108:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/lib/jazzy/doc_builder.rb:67:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.1.2/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```

**Comment by jpsim** [comment]
That bug was fixed in jazzy 0.1.3, but you're using 0.1.2. Please update and let us know if you're still having issues.
