### ISSUE TITLE
undefined method `to_S' 

### ISSUE THREAD

**Issue by mattiabugossi** [realm/jazzy#220]
``` Failed to generate documentation
/Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.0/lib/jazzy/executable.rb:33:in `execute_command': undefined method `to_S' for #<Jazzy::Executable::IO:0x007ff4164274a0> (NoMethodError)
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.0/lib/jazzy/sourcekitten.rb:83:in `run_sourcekitten'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.0/lib/jazzy/doc_builder.rb:51:in `build'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.0/bin/jazzy:15:in `<top (required)>'
	from /Users/Mattia/.rvm/rubies/ruby-2.2.0/bin/jazzy:23:in `load'
	from /Users/Mattia/.rvm/rubies/ruby-2.2.0/bin/jazzy:23:in `<main>'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/bin/ruby_executable_hooks:15:in `<main>' ```

I receive this message executing:
``` jazzy -x -workspace,MyWorkspace.xcworkspace,-scheme,MyScheme```

If I execute only ```jazzy``` everything is fine but of course I don't obtain the documentation for all the workspace.

Are there any incompatibility with Ruby 2.2?

**Comment by jpsim** [comment]
Can you please try running jazzy from the `master` branch? I think I just pushed a fix for this problem earlier today.

The [Development](https://github.com/realm/jazzy#development) section of the README explains how to do run jazzy from source.

**Comment by mattiabugossi** [comment]
Now I obtain this:
```
** BUILD SUCCEEDED **





Failed to generate documentation
	from /Users/Mattia/Downloads/jazzy-master/lib/jazzy/sourcekitten.rb:83:in `run_sourcekitten'
	from /Users/Mattia/Downloads/jazzy-master/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Users/Mattia/Downloads/jazzy-master/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Users/Mattia/Downloads/jazzy-master/lib/jazzy/doc_builder.rb:51:in `build'
	from /Users/Mattia/Downloads/jazzy-master/bin/jazzy:15:in `<main>'
```

if I run ```jazzy -x -workspace,MyWorkspace.xcworkspace,-scheme,MyScheme```
All fine if I just run ```jazzy``` but same problem as before

**Comment by jpsim** [comment]
Is there a project you can share which reproduces this issue?

**Comment by mattiabugossi** [comment]
I can create another project later, the one I'm testing I can't :smile: .

**Comment by mattiabugossi** [comment]
I tested in a much simpler project and it works, In the one I'm using we have multiple project inside and multiple submodules. But I cannot share it.

**Comment by mattiabugossi** [comment]
If you update the gem maybe I can try again with that and see if the error is different.

**Comment by jpsim** [comment]
@mattiabugossi could you try again with the latest version of jazzy available on rubygems? Thanks!

**Comment by mattiabugossi** [comment]
@jpsim trying right now.

**Comment by mattiabugossi** [comment]
@jpsim Nope, I updated the gem but same error:

```
** BUILD SUCCEEDED **





Failed to generate documentation
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.1/lib/jazzy/sourcekitten.rb:84:in `run_sourcekitten'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `build'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0@global/gems/jazzy-0.2.1/bin/jazzy:15:in `<top (required)>'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0/bin/jazzy:23:in `load'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0/bin/jazzy:23:in `<main>'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Mattia/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mattiabugossi** [comment]
@jpsim Are you guys in Mountain View?

**Comment by jpsim** [comment]
We're in SF. We'll need a repro case to make progress on this issue

**Comment by dscreve** [comment]
We have the same issue here : Our project has several schemes and targets.

**Comment by dscreve** [comment]
I tried to reproduce on another project and cannot...Is there any way that we can help you by providing some logs ?

**Comment by mattiabugossi** [comment]
@dscreve same as mine, we have several schemes and targets

**Comment by jpsim** [comment]
I'm happy to look more into it with a project that reproduces the issue. If you have logs, those *may* help too.

**Comment by jpsim** [comment]
I believe this is now fixed in the latest release of jazzy. If you see this failure again, I'd appreciate some steps I could follow to reproduce the failure. Thanks!
