### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by wangwangwar** [realm/jazzy#252]
When I use `jazzy` to parse my project, but fails to encounter such error:
```bash
fatal error: unexpectedly found nil while unwrapping an Optional value
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/sourcekitten.rb:84:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:53:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/lib/jazzy/doc_builder.rb:51:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.2.1/bin/jazzy:15:in `<top (required)>'
	from /usr/bin/jazzy:23:in `load'
	from /usr/bin/jazzy:23:in `<main>'
```
I don't know how to collect more logs and how to diagnose the error. Any suggestion? Thanks!

**Comment by wangwangwar** [comment]
Sorry, I should put the issue in project `jpsim/SourceKitten`.
