### ISSUE TITLE
Improve output when Framework has no source files

### ISSUE THREAD

**Issue by tkrajacic** [realm/jazzy#301]
When creating an empty iOS/OSX framework jazzy will produce countless screens of useless output that ends with

```
...
Failed to generate documentation
    from /Users/tkrajacic/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jazzy-0.3.1/lib/jazzy/sourcekitten.rb:115:in `run_sourcekitten'
    from /Users/tkrajacic/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:56:in `block in build'
    from /Users/tkrajacic/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `chdir'
    from /Users/tkrajacic/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jazzy-0.3.1/lib/jazzy/doc_builder.rb:54:in `build'
    from /Users/tkrajacic/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/jazzy-0.3.1/bin/jazzy:15:in `<top (required)>'
    from /Users/tkrajacic/.rbenv/gems/2.1.0/bin/jazzy:23:in `load'
    from /Users/tkrajacic/.rbenv/gems/2.1.0/bin/jazzy:23:in `<main>'
```

As soon as one adds a source file to the framework, jazzy's output is nice and concise.

One might argue that a framework without a source file is pointless anyway, but I think that jazzy should always deliver nice output, no matter what.

**Comment by jpsim** [comment]
Absolutely agreed, we should have better error handling in this case! Thanks for reporting this.

**Comment by istx25** [comment]
>Closing since this is so out of date. 
(from #303)

Doing the same here...

**Comment by jpsim** [comment]
Just because the PR attempting to fix this was outdated doesn't mean the issue goes away 😅
