### ISSUE TITLE
Cocoapods library

### ISSUE THREAD

**Issue by bolismauro** [realm/jazzy#373]
Hi everyone,
I'm trying to generate the documentation for an objc library (let's call it A) that relies on another library (let's call it B). B is imported in the A's workspace using cocoapods.
The problem I'm facing is that I always receive this error
```
LibB/ClassHeader.h:10:9: fatal error: 'B.h' file not found
```

I have the following jazzy file

```
objc_mode: true
xcodebuild_arguments: [--objc, A/A.h, -workspace,A.xcworkspace,-scheme,A,-sdk,iphonesimulator9.1]
umbrella_header: A/A.h
framework_root: A
clean: true
```

While the file where the error occurs is 
```
@import Foundation;
#import "B.h"

@interface A:B
// some properties here
@end
```

**Comment by bolismauro** [comment]
Unfortunately it doesn't work.
I also receive this additional error now
```use of '@import' when modules are disabled```

I've tried with both absolute and relative to the project root path. I also tried to remove the second `-I` as you suggested..

I honestly have not idea how to fix this

**Comment by jpsim** [comment]
If you share the project in question (or another project that's similar in its structure), I'll happily dig into it to identify the clang compiler arguments necessary to get `libClang` to parse its documentation. If you can't share that, then you'll have to wait for us to expand jazzy's support for projects with dependencies.

**Comment by bolismauro** [comment]
If I try to comment the file that causes this problem from the umbrella header (A.h) the error changes.
I have yet another class that has the same issue. This new class relies on a new library (C).
I tried to change the jazzy file according to what you suggested (but with the path to the library C)  and this time jazzy crashes

```
2015-11-16 22:07:25.192 sourcekitten[25838:3986305] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: Range or index out of bounds'

*** First throw call stack:

(

	0   CoreFoundation                      0x00007fff854bbe32 __exceptionPreprocess + 178

	1   libobjc.A.dylib                     0x00007fff858314fa objc_exception_throw + 48

	2   CoreFoundation                      0x00007fff8552265d +[NSException raise:format:] + 205

	3   Foundation                          0x00007fff87c88085 -[NSRegularExpression(NSMatching) enumerateMatchesInString:options:range:usingBlock:] + 347

	4   Foundation                          0x00007fff87c87f18 -[NSRegularExpression(NSMatching) matchesInString:options:range:] + 159

	5   SourceKittenFramework               0x000000010ea1be46 _TTSf4g_n___TF21SourceKittenFramework11insertMarksFTGSaVS_17SourceDeclaration_10limitRangeGSqVSC8_NSRange__GSaS0__ + 630

	6   SourceKittenFramework               0x000000010ea1f0ff _TFF21SourceKittenFramework11insertMarksFTGSaVS_17SourceDeclaration_10limitRangeGSqVSC8_NSRange__GSaS0__U0_FS0_S0_ + 431

	7   SourceKittenFramework               0x000000010ea1f477 _TTRXFo_oV21SourceKittenFramework17SourceDeclaration_oS0_zoPSs9ErrorType__XFo_iS0__iS0_zoPS1___ + 455

	8   SourceKittenFramework               0x000000010ea1c428 _TPA__TTRXFo_oV21SourceKittenFramework17SourceDeclaration_oS0_zoPSs9ErrorType__XFo_iS0__iS0_zoPS1___ + 72

	9   SourceKittenFramework               0x000000010ea22d75 _TTSf4g_n___TTSg5GSaV21SourceKittenFramework17SourceDeclaration_GSaS0__Ss14CollectionTypeSs_GVSs17IndexingGeneratorGSaS0___GS2_GSaS0___Ss13GeneratorTypeSs_S0__SiSiSs16ForwardIndexTypeSs_SiSiSs18_SignedIntegerTypeSs_SiSiSs33_BuiltinIntegerLiteralConvertibleSs_Si_GVSs10ArraySliceS0__GS7_S0__Ss9IndexableSsGS7_S0__Ss12SequenceTypeSs_GS2_GS7_S0___GS2_GS7_S0___S3_Ss_S0__SiSiS4_Ss_SiSiS5_Ss_SiSiS6_Ss_Si_GS7_S0___S0__S0__S0____TFeRq_Ss14CollectionType_SsS_3mapu__Rq_S__fq_FzFzqqq_S_9GeneratorSs13GeneratorType7Elementqd__GSaqd___ + 1365

	10  SourceKittenFramework               0x000000010ea1bfea _TTSf4g_n___TF21SourceKittenFramework11insertMarksFTGSaVS_17SourceDeclaration_10limitRangeGSqVSC8_NSRange__GSaS0__ + 1050

	11  SourceKittenFramework               0x000000010e9d1b58 _TFFV21SourceKittenFramework20ClangTranslationUnitcFMS0_FT11headerFilesGSaSS_17compilerArgumentsGSaSS__S0_U3_FGSaVS_17SourceDeclaration_GSaS1__ + 24

	12  SourceKittenFramework               0x000000010e9d0f50 _TPA__TTRXFo_oGSaV21SourceKittenFramework17SourceDeclaration__oGSaS0__zoPSs9ErrorType__XFo_iGSaS0___iGSaS0__zoPS1___ + 64

	13  SourceKittenFramework               0x000000010e9d100f _TPA__TTSg5SSSSSs8HashableSs_GSaV21SourceKittenFramework17SourceDeclaration__GSaS1_____TFFe0_Rq_Ss8Hashable_21SourceKittenFrameworkVSs10Dictionary3mapu0__Rq_S__FGS1_q_q0__FzFzq0_qd__GS1_q_qd___U_FzTQd__Qd_0__TQd__Q__ + 95

	14  SourceKittenFramework               0x000000010e9d10aa _TPA__TTSg5SSSSSs8HashableSs_GSaV21SourceKittenFramework17SourceDeclaration__GSaS1_____TTRG0__Rq_Ss8Hashable_XFo_iq_iq0__iTq_qd___zoPSs9ErrorType__XFo_iTq_q0___iTq_qd___zoPS0___ + 74

	15  SourceKittenFramework               0x000000010e9e4aa8 _TTSf4g_n___TTSg5GVSs10DictionarySSGSaV21SourceKittenFramework17SourceDeclaration__GS_SSGSaS1___Ss14CollectionTypeSs_GVSs19DictionaryGeneratorSSGSaS1___GS3_SSGSaS1___Ss13GeneratorTypeSs_TSSGSaS1____GVSs15DictionaryIndexSSGSaS1___GS5_SSGSaS1___Ss16ForwardIndexTypeSs_SiSiSs18_SignedIntegerTypeSs_SiSiSs33_BuiltinIntegerLiteralConvertibleSs_VSs20_DisabledRangeIndex__GVSs5SliceGS_SSGSaS1____GS10_GS_SSGSaS1____Ss9IndexableSsGS10_GS_SSGSaS1____Ss12SequenceTypeSs_GVSs17IndexingGeneratorGS10_GS_SSGSaS1_____GS13_GS10_GS_SSGSaS1_____S4_Ss_TSSGSaS1____GS5_SSGSaS1___GS5_SSGSaS1___S6_Ss_SiSiS7_Ss_SiSiS8_Ss_S9__GS10_GS_SSGSaS1_____TSSGSaS1____TSSGSaS1____TSSGSaS1______TFeRq_Ss14CollectionType_SsS_3mapu__Rq_S__fq_FzFzqqq_S_9GeneratorSs13GeneratorType7Elementqd__GSaqd___ + 1736

	16  SourceKittenFramework               0x000000010e9d0943 _TTSf4n_n_d___TFV21SourceKittenFramework20ClangTranslationUnitCfMS0_FT11headerFilesGSaSS_17compilerArgumentsGSaSS__S0_ + 2707

	17  sourcekitten                        0x000000010e95f39b sourcekitten + 33691

	18  sourcekitten                        0x000000010e959d6c sourcekitten + 11628

	19  sourcekitten                        0x000000010e959e13 sourcekitten + 11795

	20  Result                              0x000000010e9ae20a _TFO6Result6Result8analysisu0__Rq0_Ss9ErrorType_fGS0_q_q0__FT9ifSuccessFq_qd__9ifFailureFq0_qd___qd__ + 378

	21  Result                              0x000000010e9af45b _TTWu0_Rq0_Ss9ErrorType_GO6Result6Resultq_q0__S0_10ResultTypeS0_FS2_8analysisu__Rq_S2__fq_FT9ifSuccessFqq_S2_5Valueqd__9ifFailureFqq_S2_5Errorqd___qd__ + 235

	22  Result                              0x000000010e9acaf1 _TFeRq_6Result10ResultType_S_S0_7flatMapu__Rq_S0__fq_FFqq_S0_5ValueGOS_6Resultqd__qq_S0_5Error_GS1_qd__qq_S0_5Error_ + 145

	23  sourcekitten                        0x000000010e95965e sourcekitten + 9822

	24  Commandant                          0x000000010e97d83e _TPA__TFFV10Commandant10AnyCommandcu__Rqd__S_11CommandTypezq_qqd__S1_11ClientError_FMGS0_q__Fqd__GS0_q__U_FOS_11CommandModeGO6Result6ResultT_GOS_15CommandantErrorQd____ + 94

	25  Commandant                          0x000000010e97d5a1 _TFC10Commandant15CommandRegistry10runCommandurfGS0_q__FTSS9argumentsGSaSS__GSqGO6Result6ResultT_GOS_15CommandantErrorq____ + 273

	26  Commandant                          0x000000010e97db87 _TFC10Commandant15CommandRegistry4mainurfGS0_q__FT9argumentsGSaSS_11defaultVerbSS12errorHandlerFq_T__T_ + 503

	27  Commandant                          0x000000010e97d987 _TFC10Commandant15CommandRegistry4mainurfGS0_q__FT11defaultVerbSS12errorHandlerFq_T__T_ + 135

	28  sourcekitten                        0x000000010e958ff0 sourcekitten + 8176

	29  libdyld.dylib                       0x00007fff8da7e5ad start + 1

	30  ???                                 0x000000000000000c 0x0 + 12

)

libc++abi.dylib: terminating with uncaught exception of type NSException
	from /Users/bolismauro/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/sourcekitten.rb:136:in `run_sourcekitten'
	from /Users/bolismauro/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Users/bolismauro/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Users/bolismauro/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Users/bolismauro/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/jazzy-0.4.0/bin/jazzy:15:in `<top (required)>'
	from /Users/bolismauro/.rbenv/versions/2.0.0-p645/bin/jazzy:23:in `load'
	from /Users/bolismauro/.rbenv/versions/2.0.0-p645/bin/jazzy:23:in `<main>'````

**Comment by bolismauro** [comment]
@jpsim unfortunately I can't share anything of that..
I'm happy to wait.
Thank you for your help :)

**Comment by jpsim** [comment]
That looks like #370, which was just fixed.

**Comment by jpsim** [comment]
It's unclear to me what this issue is tracking anymore and my last comment seemed to indicate that this was all fixed, so I'll close this ticket. Please open a new issue if you're still having problems with jazzy.
