### ISSUE TITLE
Undefined variable 'podspec' in readme_generator.rb

### ISSUE THREAD

**Issue by razvandub** [realm/jazzy#385]
**Command:** jazzy 

**Trace:** 

```
`/Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/readme_generator.rb:34:in `generated_readme': undefined local variable or method `podspec' for Jazzy::ReadmeGenerator:Module (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/readme_generator.rb:13:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:196:in `document_index'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:297:in `document'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:82:in `block (2 levels) in build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:81:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:81:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:81:in `block in build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:92:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:92:in `block in each_doc'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:88:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:88:in `each_doc'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:77:in `build_docs'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:124:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/lib/jazzy/doc_builder.rb:68:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.4.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'`
```

**Workaround:** Remove the podspec file.

**Comment by jpsim** [comment]
thanks for reporting this issue. I hope one of us can take some time to identify what's going on here.

**Comment by pcantrell** [comment]
I think this was my fault. Investigating.

**Comment by romainbiard** [comment]
+1 . Disabling Jazzy or Remove the podspec file as a workaround

**Comment by pcantrell** [comment]
@razvandub @romainbiard If you get a chance

**Comment by razvandub** [comment]
@pcantrell Looking good, thanks.
