### ISSUE TITLE
Runtime error: private method `load' called for Psych:Module (NoMethodError)

### ISSUE THREAD

**Issue by svkurowski** [realm/jazzy#414]
I get the following error when executing `jazzy`. Same happens when I execute `jazzy -h`.

Ruby version: `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]`
Gem Version: `2.4.5`
OS: Mac OS X El Capitan

```Bash
# jazzy
/Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge/lexers/apache.rb:16:in `<class:Apache>': private method `load' called for Psych:Module (NoMethodError)
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge/lexers/apache.rb:5:in `<module:Lexers>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge/lexers/apache.rb:4:in `<module:Rouge>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge/lexers/apache.rb:3:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge/lexer.rb:443:in `load'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge/lexer.rb:443:in `load_lexer'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge.rb:45:in `block in <top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge.rb:44:in `each'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rouge-1.10.1/lib/rouge.rb:44:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jazzy-0.4.1/lib/jazzy/jazzy_markdown.rb:2:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jazzy-0.4.1/lib/jazzy/doc.rb:7:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jazzy-0.4.1/lib/jazzy/config.rb:5:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jazzy-0.4.1/lib/jazzy.rb:1:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
  from /Users/username/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/jazzy-0.4.1/bin/jazzy:13:in `<top (required)>'
  from /Users/username/.rbenv/versions/2.2.2/bin/jazzy:23:in `load'
  from /Users/username/.rbenv/versions/2.2.2/bin/jazzy:23:in `<main>'
```

**Comment by segiddins** [comment]
What's the output of `gem list --local | grep psych` ?

**Comment by jpsim** [comment]
Seems like a gem configuration issue, since rouge can't even be `required`. File an issue with them?

**Comment by segiddins** [comment]
It's actually probably a rubygems configuration issue -- we've seen this happen sporadically on CocoaPods before. Answer is either to install a new version of psych or uninstall the existing one, I can't remember which.

**Comment by svkurowski** [comment]
```Bash
# gem list --local | grep psych
psych (2.0.15, 2.0.8)

# gem uninstall psych
Successfully uninstalled psych-2.0.15

# gem install psych
Fetching: psych-2.0.16.gem (100%)
Building native extensions.  This could take a while...
Successfully installed psych-2.0.16
1 gem installed

# gem list --local | grep psych
psych (2.0.16, 2.0.8)
```
But still the same error happens.

**Comment by svkurowski** [comment]
Okay, I just fixed this by reinstalling the `rouge` gem.
To do so I had to uninstall `jekyll` and `jazzy`, then install `jazzy` again.

**Comment by jpsim** [comment]
¯\_(ツ)_/¯ ruby
