### ISSUE TITLE
XCode 7.2: `run_sourcekitten': Unable to find an Xcode with swift version 2.1.

### ISSUE THREAD

**Issue by dockay** [realm/jazzy#419]
I just installed jazzy from a gem via

```gem install jazzy```

```jazzy -v jazzy version: 0.4.1```

I'm running ruby:
```ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]```

I already did a ```gem update```

running ```jazzy``` in my root folder of the project produces following error:

```/Users/xxx/.rvm/gems/ruby-2.2.1/gems/jazzy-0.4.1/lib/jazzy/sourcekitten.rb:137:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1. (RuntimeError)
	from /Users/xxx/.rvm/gems/ruby-2.2.1/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Users/xxx/.rvm/gems/ruby-2.2.1/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Users/xxx/.rvm/gems/ruby-2.2.1/gems/jazzy-0.4.1/lib/jazzy/doc_builder.rb:55:in `build'
	from /Users/xxx/.rvm/gems/ruby-2.2.1/gems/jazzy-0.4.1/bin/jazzy:15:in `<top (required)>'
	from /Users/xxx/.rvm/gems/ruby-2.2.1/bin/jazzy:23:in `load'
	from /Users/xxx/.rvm/gems/ruby-2.2.1/bin/jazzy:23:in `<main>'
	from /Users/xxx/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xxx/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'```

By writing I just fixed it myself haha! ;-)

For Xcode 7.2 I hade to use: 
```jazzy --swift-version 2.1.1```

**Comment by jpsim** [comment]
We just moved to Swift 2.1.1 as the default in #416.
