### ISSUE TITLE
Failed to generate documentation

### ISSUE THREAD

**Issue by malcommac** [realm/jazzy#464]
I've tried to generate documentation for a project of mine.
Simply used:
```
jazzy --clean --github_url https://github.com/malcommac/SwiftDate.git
```

But it fails with error:
```
danielemm:~ danielemm$ jazzy --clean --github_url https://github.com/malcommac/SwiftDate.git
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/r9/kbkgfgjd3knf2kjlb9ptcvc00000gn/T/xcodebuild-A86A6CA8-D804-48D2-8D66-27DE3FA4EC2B.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/r9/kbkgfgjd3knf2kjlb9ptcvc00000gn/T/xcodebuild-A86A6CA8-D804-48D2-8D66-27DE3FA4EC2B.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:57:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/lib/jazzy/doc_builder.rb:55:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.5.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

Also tried using
```
sudo xcode-select -switch /Applications/Xcode.app/
```
(I've also a beta version of xcode).
 Any idea?

**Comment by anshulsolanki89** [comment]
Try to use it by specifying the swift version jazzy --swift-version=2.1.

**Comment by jpsim** [comment]
@malcommac what's the contents of `/var/folders/r9/kbkgfgjd3knf2kjlb9ptcvc00000gn/T/xcodebuild-A86A6CA8-D804-48D2-8D66-27DE3FA4EC2B.log`? Did you try @anshulsolanki89's recommendation?

We'll reopen this issue if we hear back from you with actionable information.
