### ISSUE TITLE
libclang: crash detected during parsing

### ISSUE THREAD

**Issue by TimurKhay** [realm/jazzy#479]
Having problems generating docs for objective-c dynamic framework

jazzy version: 0.5.0
xcode version: 7.2
Mac OSX: 10.11.1

Used:

```
jazzy \
  --objc \
  --clean \
  --author Octabrain \
  --author_url http://octabrain.com \
  --module-version 1.0 \
  --umbrella-header OCBReality/OCBReality.h \
  --framework-root . \
  --module OCBReality \
  --sdk iphoneos \
  --xcodebuild-arguments --objc,OCBReality/OCBReality.h,-x,objective-c,-isysroot,$(xcrun --show-sdk-path --sdk iphoneos),-I,$(pwd),-scheme,GatewayDynamic
```

Output:

```
libclang: crash detected during parsing: {
  'source_filename' : 'OCBReality/OCBReality.h'
  'command_line_args' : ['-x', 'objective-c', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk', '-I', '/Users/timur/octabrain/OCBReality/OCBReality', '-scheme', 'GatewayDynamic'],
  'unsaved_files' : [],
  'options' : 1,
}
building site
jam out ♪♫ to your fresh new docs in `docs`
```

Docs created, but it didnt parse anything.
I read some related issues, but could not find solution.

**Comment by donie-inhance** [comment]
```
libclang: crash detected during parsing: {
  'source_filename' : ''
  'command_line_args' : ['-x', 'objective-c', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk', '-I', '/Users/user/Documents/iOS/Project/Modules/Features/Feature1'],
  'unsaved_files' : [],
  'options' : 1,
}
building site
jam out ♪♫ to your fresh new docs in `docs`
```

Same here but noting in generated files as expected.

**Comment by jpsim** [comment]
Hi @TimurKhay and @donie-inhance! Sorry for the delay in getting back to you on this. Is there any chance you could share steps for me to reproduce this? I'm assuming this happens when clang can't find all of the necessary headers to resolve its imports, but I'd need to see your examples to know for sure.

**Comment by gbernady** [comment]
Here's a sample project - [Foo.zip](https://github.com/realm/jazzy/files/207109/Foo.zip)

I just ran it on my second machine and:
* jazzy 0.5.0 does not report any crashes or errors, but the docs are empty.
* jazzy 0.6.0 fails with the following error

```
    Unrecognized arguments: -x, -soiryt, -I, -awrpcosek, -semch
    /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "Libraries/Bar/Bar/Bar.h", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk", "-I", "/Users/gregor/Downloads/Foo", "-workspace", "Foo.xcworkspace", "-scheme", "Bar"] (RuntimeError)

    Unrecognized arguments: -x, -soiryt, -I, -awrpcosek, -semch
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
        from /Users/gregor/.gem/ruby/2.3.0/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
        from /Users/gregor/.gem/ruby/2.3.0/bin/jazzy:23:in `load'
        from /Users/gregor/.gem/ruby/2.3.0/bin/jazzy:23:in `<main>'
```
I did not encounter the libclang crash however, so it may have something to do with my main machine's configuration. I will look into it tomorrow. I saw a similar problem with libclang also reported in #479.

**Comment by istx25** [comment]
@TimurKhay, @donie-inhance: Would you be able to share more information? Will be closing in two weeks if there are no new responses.

**Comment by d0n13** [comment]
Not an issue for me anyway. I never solved it and I'm not too worried at this stage.

**Comment by istx25** [comment]
Sounds good. Closing.
