### ISSUE TITLE
"Unable to find an Xcode with swift version 2.1.1"

### ISSUE THREAD

**Issue by LeoNatan** [realm/jazzy#506]
```
/Users/leonatan/Desktop/Aroesti/CPMobileSDK/Utils/jazzy/lib/jazzy/sourcekitten.rb:139:in `run_sourcekitten': Unable to find an Xcode with swift version 2.1.1. (RuntimeError)
	from /Users/leonatan/Desktop/Aroesti/CPMobileSDK/Utils/jazzy/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Users/leonatan/Desktop/Aroesti/CPMobileSDK/Utils/jazzy/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Users/leonatan/Desktop/Aroesti/CPMobileSDK/Utils/jazzy/lib/jazzy/doc_builder.rb:54:in `build'
	from /Users/leonatan/Desktop/Aroesti/CPMobileSDK/Utils/jazzy/bin/jazzy:15:in `<main>'
```

Get this with Xcode 7.3, on latest master commit (cc6d813).
I assume this is due to SourceKitten not supporting Swift 2.2 yet?

**Comment by segiddins** [comment]
Yes, and in future you can pass `--swift-version=2.3` if you want to use a non-default swift version with jazzy.

**Comment by LeoNatan** [comment]
It worked, thanks so much!
