### ISSUE TITLE
iwedr rrroe

### ISSUE THREAD

**Issue by jcayzac** [realm/jazzy#520]
Hi,

I'm trying to build the documentation for an Objective-C framework `Foo`, but getting a weird, funny error.

```
jazzy --objc -c \
  --module-version "1.1.4"  \
  --umbrella-header "Foo/Foo.h" \
  --sdk "iphonesimulator" \
  -x "-workspace,Foo.xcworkspace,-scheme,Foo" \
  --framework-root . \
  -m "Foo"

Unrecognized arguments: -awrpcosek, -semch
/Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-workspace", "Foo.xcworkspace", "-scheme", "Foo"] (RuntimeError)

Unrecognized arguments: -awrpcosek, -semch
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
	from /Users/bob.coder/.gems/bin/jazzy:23:in `load'
	from /Users/bob.coder/.gems/bin/jazzy:23:in `<main>'
```

`awrpcosek` and `semch` look like a random reshuffle of `workspace` and `scheme`. Looking at `lib/jazzy/sourcekitten.rb:142` doesn't give any obvious reason.

**Comment by jcayzac** [comment]
More info on my environment:

```
$ sourcekitten version
0.12.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65
$ uname -v
Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
```

I installed sourcekitten with Homebrew.

**Comment by jpsim** [comment]
This recently changed in jazzy 0.6.0, you'll need to prepend `--` to your xcodebuild arguments: `-x "--,-workspace,Foo.xcworkspace,-scheme,Foo"`. Could you please try this and report again?

**Comment by jcayzac** [comment]
Hmm now I get the following output:

```
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/r3/k_9mtrkj1jg9wm5z964v8ph00000gp/T/xcodebuild-8BBA2080-F80F-436E-A90E-AB18649D8ECF.log
Failed to generate documentation
/Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--", "-workspace", "Foo.xcworkspace", "-scheme", "Foo"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/r3/k_9mtrkj1jg9wm5z964v8ph00000gp/T/xcodebuild-8BBA2080-F80F-436E-A90E-AB18649D8ECF.log

Failed to generate documentation
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
	from /Users/bob.coder/.gems/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
	from /Users/bob.coder/.gems/bin/jazzy:23:in `load'
	from /Users/bob.coder/.gems/bin/jazzy:23:in `<main>'
```

The xcodebuild log ends up with:

```
    /usr/bin/touch -c /Users/bob.coder/FooFramework/build/Build/Products/Debug-iphoneos/Foo.framework

** BUILD SUCCEEDED **
```

I don't understand the `Please confirm that `xcodebuild` is building a Swift module.` part, since I am clearly building an ObjC module.

**Comment by jpsim** [comment]
Passing extra arguments to xcodebuild is using jazzy in "expert mode" :stuck_out_tongue:. You'll need to also tell SourceKitten that you're in Objective-C mode. Try this:

```
jazzy --objc -c \
  --module-version "1.1.4"  \
  --umbrella-header "Foo/Foo.h" \
  --sdk "iphonesimulator" \
  -x "--objc,--,-workspace,Foo.xcworkspace,-scheme,Foo" \
  --framework-root . \
  -m "Foo"
```

**Comment by jcayzac** [comment]
Thanks! This solved the problem! Should I close the issue or would you like to keep it open for maybe documenting the behavior?

**Comment by jpsim** [comment]
Let's close this as we have a number of issues tracking how to improve this, in several different ways. As you can see, the current Objective-C interface is extremely unforgiving and difficult to understand.
