### ISSUE TITLE
jazzy failed to generate documentation by set -x argument,but xcodebuild success

### ISSUE THREAD

**Issue by Eveninger** [realm/jazzy#529]
the command is `jazzy -x  -workspace,ReactiveCocoa.xcworkspace,-scheme,ReactiveCocoa-iOS` and output is 

```
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/cl/d2j6l1rx7qvcpm0cl143st480000gn/T/xcodebuild-CEA78C6A-3662-4626-BA5C-BF9D84F98801.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--", "-workspace", "ReactiveCocoa.xcworkspace", "-scheme", "ReactiveCocoa-iOS"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/cl/d2j6l1rx7qvcpm0cl143st480000gn/T/xcodebuild-CEA78C6A-3662-4626-BA5C-BF9D84F98801.log

Failed to generate documentation
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
    from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
    from /usr/local/bin/jazzy:23:in `load'
    from /usr/local/bin/jazzy:23:in `<main>'
```

however, build ReactiveCocoa.xcworkspace by using `xcodebuild  -workspace ReactiveCocoa.xcworkspace -scheme ReactiveCocoa-iOS` can success
are there any way to solve?

**Comment by jpsim** [comment]
What's the log output? i.e. the contents of `/var/folders/cl/d2j6l1rx7qvcpm0cl143st480000gn/T/xcodebuild-CEA78C6A-3662-4626-BA5C-BF9D84F98801.log`?

**Comment by Eveninger** [comment]
[Uploading xcodebuild-CEA78C6A-3662-4626-BA5C-BF9D84F98801.txt…]()
this is the log output that shows xcodebuild building success

**Comment by Eveninger** [comment]
[Uploading xcodebuild-CEA78C6A-3662-4626-BA5C-BF9D84F98801.txt…]()

**Comment by Eveninger** [comment]
[xcodebuild-CEA78C6A-3662-4626-BA5C-BF9D84F98801.txt](https://github.com/realm/jazzy/files/222667/xcodebuild-CEA78C6A-3662-4626-BA5C-BF9D84F98801.txt)

**Comment by jpsim** [comment]
I see. You'll need to specify the module name since it's different than the scheme's that's automatically detected (`ReactiveCocoa` vs `ReactiveCocoa-iOS`):

```
jazzy -m ReactiveCocoa -x -workspace,ReactiveCocoa.xcworkspace,-scheme,ReactiveCocoa-iOS
```

Which I should add is equivalent to just running `jazzy` with no arguments.

**Comment by Eveninger** [comment]
Thanks for reply.
But if I use `jazzy` or `jazzy -m ReactiveCocoa -x -workspace,ReactiveCocoa.xcworkspace,-scheme,ReactiveCocoa-iOS`, `jazzy`cannot generate whole document. A part of references is undocumented like this:
![image](https://cloud.githubusercontent.com/assets/12775863/14626455/0990eeac-061e-11e6-8e1b-2512bb85eba8.png)
and the most of the undocumented items print log like this:
```
`mainQueueScheduler` has no USR. First make sure all modules used in your project have been imported. If all used modules are imported, please report this problem by filing an issue at https://github.com/realm/jazzy/issues along with your Xcode project. If this token is declared in an `#if` block, please ignore this message.
```
Maybe the comment of ReactiveCocoa has problem, because I use `jazzy` to generate `Alamofire` document and it's pretty good!
Thank you very much!

**Comment by jpsim** [comment]
I'm sorry I don't have time to look into this right now. This might be a bug in jazzy but I'm not sure. If another contributor can look into this, then great. Otherwise I'll investigate when I have some time.

**Comment by emoleumassi** [comment]
Something new? i have the same issue

**Comment by jpsim** [comment]
@emoleumassi best way to make progress on this (or any issue really) is to share detailed steps that I can take to reproduce the issue.

**Comment by istx25** [comment]
Would love it if someone could share more information about this issue so we can reproduce it properly and come up with a fix. A minimal test project would also be awesome. Closing in two weeks if there is no activity here. Cheers!

**Comment by awedeebawe** [comment]
@istx25 I noticed, that when I pass scheme with whitespace (e.g "MyTarget Dev"), the build succeeds, but the jazzy-fication fails with the same reason the OP found.
When I pass scheme like "MyTarget", the build succeeds, and the parsing - too.

May be SourceKitten doesn't parse the escaped whitespace properly.

**Comment by istx25** [comment]
Hi @awedeebawe, would you be able to file a new issue with a test project that reproduces this problem as well as reference this issue? From there we can evaluate the problem and find a fix!! :)
