### ISSUE TITLE
@compatibility_alias statements cause SourceKitten to barf

### ISSUE THREAD

**Issue by frankus** [realm/jazzy#543]
This might be a SourceKitten issue, but it's probably useful to have it documented here:

If your source file includes a @compatibility_alias declaration, you will get the following output: 

```
fatal error: Unsupported CXCursorKind: UnexposedDecl: file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/ObjCDeclarationKind.swift, line 71
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "/Users/<redacted_path_would_go_here>.h", "--", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk", "-I", "/Users/<redacted_path_would_go_here>"] (RuntimeError)

fatal error: Unsupported CXCursorKind: UnexposedDecl: file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/ObjCDeclarationKind.swift, line 71
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

A workaround is to comment out the declaration, generate your docs, and then uncomment.

**Comment by jpsim** [comment]
Thanks for reporting this! I'm sorry I was so let to get to this, but I just pushed a fix in #562... would you mind confirming that you can now generate docs for your project using that branch? Thanks!
