### ISSUE TITLE
does not build documenation on "Realm" master 

### ISSUE THREAD

**Issue by alokc83** [realm/jazzy#550]
I am using both of your tools/files and your documentation. 
Its not building out of the box 
spitting these error out : 

```
> `className` has no USR. First make sure all modules used in your project have been imported. If all used modules are imported, please report this problem by filing an issue at https://github.com/realm/jazzy/issues along with your Xcode project. If this token is declared in an `#if` block, please ignore this message.
> building site
> /Users/user578/.rvm/gems/ruby-2.2.3@global/gems/mustache-0.99.8/lib/mustache/settings.rb:142:in `read': No such file or directory @ rb_sysopen - /Users/user578/Documents/GitHub/realm-cocoa/docs/themes/templates/doc.mustache (Errno::ENOENT)
>   from /Users/user578/.rvm/gems/ruby-2.2.3@global/gems/mustache-0.99.8/lib/mustache/settings.rb:142:in `template'
>   from /Users/user578/.rvm/gems/ruby-2.2.3@global/gems/mustache-0.99.8/lib/mustache/settings.rb:157:in `template'
>   from /Users/user578/.rvm/gems/ruby-2.2.3@global/gems/mustache-0.99.8/lib/mustache.rb:109:in `render'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:365:in `document'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:81:in `block (2 levels) in build_docs'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:80:in `open'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:80:in `open'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:80:in `block in build_docs'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:91:in `call'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:91:in `block in each_doc'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:87:in `each'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:87:in `each_doc'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:76:in `build_docs'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:114:in `build_site'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:141:in `build_docs_for_sourcekitten_output'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:67:in `build'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/bin/jazzy:23:in `load'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/bin/jazzy:23:in `<main>'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
>   from /Users/user578/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Any suggestions ?

**Comment by jpsim** [comment]
The way Realm builds docs is using the `./build.sh docs` command. The "`className` has no USR" warning is expected and not actually problematic.

I don't know if there are any known issues in Ruby 2.2.3 that could be causing this, I'm using `2.2.4p230` locally, jazzy has CI using `2.0.0p643` and Realm generates its docs on CI with `2.0.0p648`.

**Comment by PumpMagic** [comment]
This is caused by invoking Jazzy with a nonexistent custom theme. It's worth noting that the Jazzy readme's example command uses a custom theme, so new users pasting example commands without too much thought will experience this.

Sorry to necromance, but I experienced this myself and came here from a Google search, thought it might be useful for others.
