### ISSUE TITLE
Jazzy error when specifying --objc argument

### ISSUE THREAD

**Issue by sitefeng** [realm/jazzy#559]
When running jazzy with the following arguments, the command runs perfectly without `--objc`, but when `--objc` is added, jazzy shows error.

```
jazzy \
  --min-acl private \
  --objc \
  --clean \
  --author Project \
  --author_url https://project.com \
  --github_url https://github.com/repository-name/project-name \
  --module-version 1.11.1 \
  --output ../jazzy_docs \
  --theme apple \
  --copyright repository-name_2016 \
  --readme README.mdown \
  --xcodebuild-arguments -scheme,repository-name,-workspace,project-name.xcworkspace,-configuration,Debug \
  clean build \
```

jazzy displays error

```
16:08:01]: fastlane finished with errors

[!] Exit status of command 'sh jazzy.sh' was 1 instead of 0.
Unrecognized arguments: -semch, -awrpcosek, -aircnofgut
/Users/project-name/project-name/project-name/project-name-ios/Vendor/bundle/ruby/2.2.0/gems/jazzy-0.6.0/lib/jazzy/executable.rb:36:in `execute_command': /Users/project-name/project-name/project-name/project-name-ios/Vendor/bundle/ruby/2.2.0/gems/jazzy-0.6.0/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "-scheme", "project-name", "-workspace", "project-name.xcworkspace", "-configuration", "Debug"] (RuntimeError)

Unrecognized arguments: -semch, -awrpcosek, -aircnofgut
    from /Users/project-name/project-name/project-name/project-name-ios/Vendor/bundle/ruby/2.2.0/gems/jazzy-0.6.0/lib/jazzy/sourcekitten.rb:142:in `run_sourcekitten'
    from /Users/project-name/project-name/project-name/project-name-ios/Vendor/bundle/ruby/2.2.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:56:in `block in build'
    from /Users/project-name/project-name/project-name/project-name-ios/Vendor/bundle/ruby/2.2.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `chdir'
    from /Users/project-name/project-name/project-name/project-name-ios/Vendor/bundle/ruby/2.2.0/gems/jazzy-0.6.0/lib/jazzy/doc_builder.rb:54:in `build'
    from /Users/project-name/project-name/project-name/project-name-ios/Vendor/bundle/ruby/2.2.0/gems/jazzy-0.6.0/bin/jazzy:15:in `<top (required)>'
    from /Users/project-name/project-name/project-name/project-name-ios/vendor/bundle/ruby/2.2.0/bin/jazzy:23:in `load'
    from /Users/project-name/project-name/project-name/project-name-ios/vendor/bundle/ruby/2.2.0/bin/jazzy:23:in `<main>'
****
```

**Comment by jpsim** [comment]
You need to pass `--` at the start of the xcodebuild arguments:

```
jazzy \
  --min-acl private \
  --objc \
  --clean \
  --author Project \
  --author_url https://project.com \
  --github_url https://github.com/repository-name/project-name \
  --module-version 1.11.1 \
  --output ../jazzy_docs \
  --theme apple \
  --copyright repository-name_2016 \
  --readme README.mdown \
  --xcodebuild-arguments -- -scheme,repository-name,-workspace,project-name.xcworkspace,-configuration,Debug \
  clean build \
```

**Comment by ohnit** [comment]
The `--` didn't work for me. 

```
jazzy \
--clean \
--objc \
--sdk iphone \
--min-acl private \
--xcodebuild-arguments -- -scheme,MyApp
```

outputs this:
```
/Users/me/.gem/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:57:in `read': No such file or directory - /Users/me/Documents/Projects/App/cheme,MyApp (Errno::ENOENT)
	from /Users/me/.gem/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:57:in `read'
	from /Users/me/.gem/gems/jazzy-0.7.0/lib/jazzy/doc_builder.rb:57:in `build'
	from /Users/me/.gem/gems/jazzy-0.7.0/bin/jazzy:15:in `<top (required)>'
	from /Users/me/.gem/bin/jazzy:23:in `load'
	from /Users/me/.gem/bin/jazzy:23:in `<main>'
```

**Comment by mobdim** [comment]
I also get an error when adding:
`objc: true`
in .jazzy.uml


`Unrecognized arguments: -awrpcosek, -semch`

**Comment by AtharvaVaidya** [comment]
I'm still having this issue.

**Comment by jpsim** [comment]
@mobdim @AtharvaVaidya if you see mangled arguments, you're probably missing the `--`

**Comment by johnfairh** [comment]
Closing, inactive.
