### ISSUE TITLE
Jazzy is not building for objective-c framework.

### ISSUE THREAD

**Issue by vnramachandra** [realm/jazzy#587]
Hi Jazzy team,

      Recently I updated jazzy from version 0.5.0 to 0.6.3. Previously I used following command in shell script to generate objective-c documentation and it was working fine. 

```
jazzy --objc -x --objc,../Builds/blah/blah.framework/Headers/blah.h,-x,objective-c,-isysroot,`xcrun --show-sdk-path --sdk iphoneos`, --module Blah --output ../Builds/Docs/Objective-C
```

After updating jazzy to 0.6.3 it started to throw following errors.

```
Unrecognized arguments: -x, -soiryt
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.6.3/lib/jazzy/sourcekitten.rb:146:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.6.3/lib/jazzy/doc_builder.rb:64:in `block in build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.6.3/lib/jazzy/doc_builder.rb:62:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.6.3/lib/jazzy/doc_builder.rb:62:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.6.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

Can anybody tell me what's happening over here? Should I change something in the code.

**Comment by jpsim** [comment]
Some changes happened upstream that weren't gracefully handled when we incorporated them.

You now need to pass `--` ahead of clang arguments:

```diff
- jazzy --objc -x --objc,../Builds/blah/blah.framework/Headers/blah.h,-x,objective-c,-isysroot,`xcrun --show-sdk-path --sdk iphoneos`, --module Blah --output ../Builds/Docs/Objective-C
+ jazzy --objc -x --objc,../Builds/blah/blah.framework/Headers/blah.h,--,-x,objective-c,-isysroot,`xcrun --show-sdk-path --sdk iphoneos`, --module Blah --output ../Builds/Docs/Objective-C
```

**Comment by vnramachandra** [comment]
Thank you JP, worked like a charm.
