### ISSUE TITLE
Fatal Issue, Can not find UIKIT for objective C project

### ISSUE THREAD

**Issue by ort11** [realm/jazzy#608]
XCODE 7.3.1
Jazzy 0.7.0

Have been using for SWIFT build fine, trying to get to work with an Objective C Build.

jazzy \
--objc \
--umbrella-header MediumSDKObj-C/AppDelegate.h
--sdk iphoneos \
--clean \
--author "Author" \
--copyright "Copyright" \
--xcodebuild-arguments '-project,mediumSDKObj-C.xcodeproj,-scheme,mediumSDKObj-C' \
--min-acl internal

Output

fatal error: 'UIKit/UIKit.h' file not found

**Comment by yeluolei** [comment]
same issue with the same environment. and the error include such things

```
fatal error: Couldn't get category name: file /Users/jp/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/Clang+SourceKitten.swift, line 109
```

**Comment by narlei** [comment]
Same issue here.

**Comment by pronebird** [comment]
Set `--framework-root MediumSDKObj-C`, that helped me to solve the same issue.

**Comment by AtharvaVaidya** [comment]
I'm facing this issue as well.

**Comment by jpsim** [comment]
Full steps to repro would be appreciated.

**Comment by Nelyus** [comment]
I have the same error with:
````
$> cat .jazzy.yml
objc: true
sdk: iphoneos
$> jazzy --module-version 2.21.01 --module MyModule \
 --xcodebuild-arguments --objc,Headers/Public/MyModule.h,--,--arch,armv7
````

However it works by specifying the full sdk path:
````shell
jazzy --module-version 2.21.01 --module MyModule \
 --xcodebuild-arguments --objc,Headers/Public/MyModule.h,--,--arch,armv7,-isysroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk
````

**Comment by petrmanek** [comment]
Also got this. Have you found any solution?

**Comment by johnfairh** [comment]
It means the sdk/sysroot is not being set correctly -- check the README for examples of running against Objective-C projects.  Please post your jazzy command / config file if still a problem (and point to your project if possible!)

**Comment by johnfairh** [comment]
Closing: inactive.

**Comment by poborin** [comment]
hmm... I've got the same issue with the Xcode 11.4. Meanwhile, it works fine with the Xcode 11.3

```
RuntimeError: /Users/PavelOborin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jazzy-0.13.2/bin/sourcekitten ["doc", "--objc", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/PublicHeaders/BDPointSDK.h", "--", "-x", "objective-c", "-isysroot", "/Applications/Xcode-11.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.4.sdk", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK", "-fmodules", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Map/Renderer/Factory", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Map/Renderer/Beacon", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Map/Renderer", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Map/Overlay/Fence", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Map/Overlay/Beacon", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Map/Overlay", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Map", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View/Window", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI/View", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/UI", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/CommonCrypto", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/ModuleMap", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Configuration", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/UIKit", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing/Sensors", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing/ZoneManager/Actions", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing/ZoneManager", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing/Fence\\ Tracker", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing/Beacon\\ Tracker", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing/Activity\\ Detection", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing/Accuracy\\ Modifier", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused/Signal\\ Processing", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift_unused", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/ZoneManager/Conditions", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/ZoneManager/Actions", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/ZoneManager/Geofeatures/Fences", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/ZoneManager/Geofeatures/Beacons", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/ZoneManager/Geofeatures", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/ZoneManager", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Configuration", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Logger", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/RainbowAPIClientData", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Timers", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Network", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Hashing", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Storage", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Extensions", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/TestManagementAPI", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Keychain", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/External/Promises", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/External", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support/Signaling", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Support", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Geometry", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/Pagination", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/Sensors", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/Fence\\ Tracker", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/Rules\\ Provider", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/NearGeoFenceSuppressor", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/Accuracy\\ Modifier", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/Periodic\\ Polling", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/GPS\\ Detection", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing/Starvation\\ Detection", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift/Signal\\ Processing", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Swift", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Model/Collection", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Model/TriggerEvent", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Model/Info", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Model/Device", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Model", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/BDDataModel.xcdatamodeld/BDDataModel_1.13.xcdatamodel", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/BDDataModel.xcdatamodeld", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/AppDelegate", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/PublicHeaders", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Data", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Tracker", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Rule/Source", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Rule/StateManager", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Rule/TemporalStateController", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Rule", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Action", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Filter/Schedule", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Filter", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/CheckIn", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process/Session", "-I", "/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/Process"]

/Users/PavelOborin/projects/point_sdk_ios/BDPointSDK/PublicHeaders/BDPointSDK.h:8:9: fatal error: could not build module 'UIKit'

Fatal error: Couldn't get category name: file /Users/johnf/project/jazzy/SourceKitten/Source/SourceKittenFramework/Clang+SourceKitten.swift, line 127

  /Users/PavelOborin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jazzy-0.13.2/lib/jazzy/executable.rb:36:in `execute_command'
  /Users/PavelOborin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jazzy-0.13.2/lib/jazzy/sourcekitten.rb:266:in `run_sourcekitten'
  /Users/PavelOborin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:78:in `block in build'
  /Users/PavelOborin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:76:in `chdir'
  /Users/PavelOborin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jazzy-0.13.2/lib/jazzy/doc_builder.rb:76:in `build'
  /Users/PavelOborin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jazzy-0.13.2/bin/jazzy:15:in `<top (required)>'
  /Users/PavelOborin/.rbenv/versions/2.5.1/bin/jazzy:23:in `load'
  /Users/PavelOborin/.rbenv/versions/2.5.1/bin/jazzy:23:in `<top (required)>'
```

**Comment by XWJACK** [comment]
> fatal error: 'UIKit/UIKit.h' file not found

Using `--sdk iphonesimulator` instead of `--sdk iphoneos`

**Comment by vikihleblya** [comment]
Run this command to create xcodeproj file:
```
$ swift package generate-xcodeproj
```

After run this command: 
```
$ jazzy \
  --module MRCalendar \
  --swift-build-tool spm \
  --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5 \
  --sdk iphonesimulator  
```
Anyway getting error `fatal error: 'UIKit/UIKit.h' file not found`

**Comment by johnfairh** [comment]
The commands above generated an xcodeproj file and then run jazzy in Swift SPM mode.

If your module is Objective C then you need to run jazzy in [ObjC mode](https://github.com/realm/jazzy#objective-c).

If you're still having problems then please open a new issue explaining your setup and what you're trying to do.
