### ISSUE TITLE
[Help] jazzy crashes with any argument ¯\_(ツ)_/¯ 

### ISSUE THREAD

**Issue by jessesquires** [realm/jazzy#652]
I'm a ruby novice, so sorry if this is trivial, but I'm not sure what the problem is. 😅 

I've looked around for help elsewhere, but didn't have any luck, so opening an issue here. 

This looks like it could be an issue in `jazzy` (not likely?), `rouge` (maybe?), or with my setup (probably).

#### Setup

- `jazzy 0.7.0`
- `Xcode 7.3.1`
- `ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]`
- using `rbenv`

#### Issue

I've never had trouble with `jazzy` before, but `0.7.0` isn't working at all for me.
I was trying to update some docs, but then I realized that every argument is crashing.

Running `jazzy -h` results in:

```bash
/usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge/lexers/apache.rb:16:in `<class:Apache>': private method `load' called for Psych:Module (NoMethodError)
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge/lexers/apache.rb:5:in `<module:Lexers>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge/lexers/apache.rb:4:in `<module:Rouge>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge/lexers/apache.rb:3:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge/lexer.rb:371:in `load'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge/lexer.rb:371:in `load_lexer'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge.rb:52:in `block in <top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge.rb:51:in `each'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/rouge-1.11.1/lib/rouge.rb:51:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/jazzy-0.7.0/lib/jazzy/jazzy_markdown.rb:2:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/jazzy-0.7.0/lib/jazzy/doc.rb:7:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/jazzy-0.7.0/lib/jazzy/config.rb:5:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/jazzy-0.7.0/lib/jazzy.rb:1:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /usr/local/var/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/jazzy-0.7.0/bin/jazzy:13:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.2.5/bin/jazzy:23:in `load'
	from /usr/local/var/rbenv/versions/2.2.5/bin/jazzy:23:in `<main>'
```

Any help/advice is appreciated!

![](https://media.giphy.com/media/xDQ3Oql1BN54c/giphy.gif)

**Comment by jessesquires** [comment]
Using `ruby 2.2.2` seems to have fixed the issue!

`ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]`

Sorry for the noise! 😄

**Comment by bolot** [comment]
I had the same crash, but since I was on `ruby 2.2.2`, my solution was different. According to a comment by @mame https://github.com/bbatsov/rubocop/issues/1510, it appears to be a `rubygems` bug and can be fixed by `[sudo] gem update --system`, which worked for me.
