### ISSUE TITLE
Danger integration broken

### ISSUE THREAD

**Issue by jpsim** [realm/jazzy#687]
Thoughts on what could be causing this @orta? https://travis-ci.org/realm/jazzy/builds/179101307

```
$ bundle exec danger || true
fatal: Couldn't find remote ref refs/pull/686/merge
bundler: failed to load command: danger (/Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: git '--git-dir=/Users/travis/build/realm/jazzy/.git' '--work-tree=/Users/travis/build/realm/jazzy' diff '--numstat' 'danger_head' 'danger_base'  2>&1:fatal: ambiguous argument 'danger_head': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'. Updating the Danger gem might fix the issue.
 #  from Dangerfile:2
 #  -------------------------------------------
 #  # Warn when there is a big PR
 >  warn("Big PR") if lines_of_code > 500
 #  
 #  -------------------------------------------
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/git-1.3.0/lib/git/lib.rb:861:in `command_lines'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/git-1.3.0/lib/git/lib.rb:362:in `diff_stats'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/git-1.3.0/lib/git/diff.rb:113:in `cache_stats'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/git-1.3.0/lib/git/diff.rb:34:in `lines'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb:42:in `lines_of_code'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:61:in `block in method_missing'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:59:in `each'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:59:in `method_missing'
  Dangerfile:2:in `block in parse'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:177:in `eval'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:177:in `block in parse'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:173:in `instance_eval'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/danger_core/dangerfile.rb:173:in `parse'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/lib/danger/commands/runner.rb:54:in `run'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.1/bin/danger:5:in `<top (required)>'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger:23:in `load'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger:23:in `<top (required)>'
```

**Comment by johnfairh** [comment]
Closing this, seems fine now.

**Comment by orta** [comment]
Oh yeah, I missed this :D
