### ISSUE TITLE
`jazzy` could not parse compiler arguments from `xcodebuild` output.

### ISSUE THREAD

**Issue by wittedhaddock** [realm/jazzy#734]
Using `jazzy version: 0.7.3` XC 8.1, if I execute `jazzy` in the root directory of my xcodeproj, I get

```Jamess-MacBook-Pro-3:Caproxient jameswilliamgraham$ jazzy 
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/3_/nqf15y4j32sf998_68kkq0j00000gn/T/xcodebuild-2C8656F2-34C3-407C-9CCC-ECFCBC626E02.log
Failed to generate documentation
/Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/gems/jazzy-0.7.3/lib/jazzy/executable.rb:36:in `execute_command': /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/gems/jazzy-0.7.3/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/3_/nqf15y4j32sf998_68kkq0j00000gn/T/xcodebuild-2C8656F2-34C3-407C-9CCC-ECFCBC626E02.log

Failed to generate documentation
	from /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/gems/jazzy-0.7.3/lib/jazzy/sourcekitten.rb:147:in `run_sourcekitten'
	from /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `build'
	from /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/gems/jazzy-0.7.3/bin/jazzy:15:in `<top (required)>'
	from /Users/jameswilliamgraham/.rvm/rubies/ruby-2.2.4/bin/jazzy:23:in `load'
	from /Users/jameswilliamgraham/.rvm/rubies/ruby-2.2.4/bin/jazzy:23:in `<main>'
	from /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

Suggested elsewhere is the removal of my existing `./docs/` directory and running `jazzy --min-acl internal` which yields the same above error output.

**Comment by jpsim** [comment]
@wittedhaddock it would help if you posted the log output: 

> Saved `xcodebuild` log file: /var/folders/3_/nqf15y4j32sf998_68kkq0j00000gn/T/xcodebuild-2C8656F2-34C3-407C-9CCC-ECFCBC626E02.log

**Comment by wittedhaddock** [comment]
@jpsim For sure!

FYI running `sudo jazzy` resolves the problem. Looks like it's just a perm issue, probably a poor first installation on my end?

```
2017-01-17 19:35:57.673 xcodebuild[20312:480541] [MT] DVTToolchain: Failed to load toolchain: <DVTFilePath:0x7faee9d784d0:'/Users/jameswilliamgraham/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain'>: Error Domain=DVTToolchainErrorDomain Code=6 "Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings" UserInfo={NSFilePath=/Users/jameswilliamgraham/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain, NSLocalizedDescription=Info.plist:OverrideBuildSettings:{SWIFT_LINK_OBJC_RUNTIME,SWIFT_DISABLE_REQUIRED_ARCLITE,ENABLE_BITCODE} must contain a string or array of strings}
Build settings from command line:
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO

2017-01-17 19:35:59.690 xcodebuild[20312:480611] couldn't read dependency graph from '/Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/dgph': Permission denied
2017-01-17 19:35:59.691 xcodebuild[20312:480611] unable to create temporary file at /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/dgph-Ks08b1MT: Permission denied
2017-01-17 19:35:59.692 xcodebuild[20312:480611]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11527/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7faeec9e2870>{number = 9, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
=== CLEAN TARGET Proxeine OF PROJECT Proxeine WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

Clean.Remove clean build/Release-iphoneos/Proxeine.framework.dSYM
    builtin-rm -rf /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Release-iphoneos/Proxeine.framework.dSYM
Error Domain=NSCocoaErrorDomain Code=513 "“Proxeine.framework.dSYM” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/Users/jameswilliamgraham/ProxyClient/Caproxient/build/Release-iphoneos/Proxeine.framework.dSYM, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7faeec7d4950 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
Command builtin-rm failed with exit code 513
2017-01-17 19:36:00.194 xcodebuild[20312:480610] couldn't read dependency graph from '/Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/dgph': Permission denied

Clean.Remove clean build/Proxeine.build/Release-iphoneos/Proxeine.build
    builtin-rm -rf /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build
Error Domain=NSCocoaErrorDomain Code=513 "“Proxeine.build” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7faeec8ea9c0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
Command builtin-rm failed with exit code 513

Clean.Remove clean build/Release-iphoneos/Proxeine.framework
    builtin-rm -rf /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Release-iphoneos/Proxeine.framework
Error Domain=NSCocoaErrorDomain Code=513 "“Proxeine.framework” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/Users/jameswilliamgraham/ProxyClient/Caproxient/build/Release-iphoneos/Proxeine.framework, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7faeeca88a70 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
Command builtin-rm failed with exit code 513

2017-01-17 19:36:00.194 xcodebuild[20312:480610] unable to create temporary file at /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/dgph-n3xXqyRP: Permission denied
** CLEAN FAILED **


The following build commands failed:
	Clean.Remove clean build/Release-iphoneos/Proxeine.framework.dSYM
	Clean.Remove clean build/Proxeine.build/Release-iphoneos/Proxeine.build
	Clean.Remove clean build/Release-iphoneos/Proxeine.framework
(3 failures)
2017-01-17 19:36:00.195 xcodebuild[20312:480610]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11527/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7faeec5b56e0>{number = 8, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
=== BUILD TARGET Proxeine OF PROJECT Proxeine WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
2017-01-17 19:36:00.260 xcodebuild[20312:480610] couldn't read dependency graph from '/Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/dgph': Permission denied
2017-01-17 19:36:00.261 xcodebuild[20312:480610] unable to create temporary file at /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/dgph-Dj8WWAKn: Permission denied
2017-01-17 19:36:00.261 xcodebuild[20312:480610]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11527/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/DependencyGraph/XCDependencyGraph.mm:688
Details:  unable to write dependency graph: Permission denied
Object:   <XCDependencyGraph>
Method:   +loadOrCreateInBuildDirectory:withTargetBuildContext:withBasePath:
Thread:   <NSThread: 0x7faeec5b56e0>{number = 8, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

Write auxiliary files
write-file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/arm64/Proxeine-OutputFileMap.json
error: Unable to write to file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/arm64/Proxeine-OutputFileMap.json (You don’t have permission to save the file “Proxeine-OutputFileMap.json” in the folder “arm64”.)
write-file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/armv7/Proxeine-OutputFileMap.json
error: Unable to write to file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/armv7/Proxeine-OutputFileMap.json (You don’t have permission to save the file “Proxeine-OutputFileMap.json” in the folder “armv7”.)
write-file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/armv7/Proxeine.LinkFileList
error: Unable to write to file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/armv7/Proxeine.LinkFileList (You don’t have permission to save the file “Proxeine.LinkFileList” in the folder “armv7”.)
write-file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/arm64/Proxeine.LinkFileList
error: Unable to write to file /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Proxeine.build/Release-iphoneos/Proxeine.build/Objects-normal/arm64/Proxeine.LinkFileList (You don’t have permission to save the file “Proxeine.LinkFileList” in the folder “arm64”.)

ProcessInfoPlistFile build/Release-iphoneos/Proxeine.framework/Info.plist Proxeine/Info.plist
    cd /Users/jameswilliamgraham/ProxyClient/Caproxient
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4/bin:/Users/jameswilliamgraham/.rvm/gems/ruby-2.2.4@global/bin:/Users/jameswilliamgraham/.rvm/rubies/ruby-2.2.4/bin:/Users/jameswilliamgraham/anaconda/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbi:/opt/local/bin:/opt/local/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/jameswilliamgraham/.rvm/bin"
    builtin-infoPlistUtility /Users/jameswilliamgraham/ProxyClient/Caproxient/Proxeine/Info.plist -expandbuildsettings -format binary -platform iphoneos -o /Users/jameswilliamgraham/ProxyClient/Caproxient/build/Release-iphoneos/Proxeine.framework/Info.plist
error: You don’t have permission to save the file “Info.plist” in the folder “Proxeine.framework”.
error: couldn't remove '/Users/jameswilliamgraham/ProxyClient/Caproxient/build/Release-iphoneos/Proxeine.framework/Info.plist' after command failed: Permission denied

** BUILD FAILED **


The following build commands failed:
	Write auxiliary files
	ProcessInfoPlistFile build/Release-iphoneos/Proxeine.framework/Info.plist Proxeine/Info.plist
(2 failures)
```

**Comment by jpsim** [comment]
Yes, that seems to be the problem.

**Comment by wittedhaddock** [comment]
Thank you!

**Comment by DevelopingMe** [comment]
I am having the same issue... I tried running sudo jazzy and rendering the same error message. Is there any videos on how to run Jazzy?

**Comment by jpsim** [comment]
@DevelopingMe please file an issue with steps to reproduce so we can help you.
