### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nrbrook** [realm/jazzy#735]
I've just installed and run, but it is crashing:

```
$ jazzy --objc --clean --author Nick --module Module --output ./docs
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "''", "--", "-x", "objective-c", "-isysroot", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-I", "''"] (RuntimeError)

	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/sourcekitten.rb:147:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

**Comment by jpsim** [comment]
From the README:

> To generate documentation for Objective-C headers, you must pass the following
parameters to jazzy:
>
> * `--objc`
> * `--umbrella-header ...`
> * `-framework-root ...`
> * `--sdk [iphone|watch|appletv][os|simulator]|macosx` (optional, default value
   of `macosx`)

Looks like you're missing `--umbrella-header` and `-framework-root`

**Comment by johnfairh** [comment]
Closing, answered.
