### ISSUE TITLE
Jazzy throwing RunTimeError for watchOS framework.

### ISSUE THREAD

**Issue by vnramachandra** [realm/jazzy#738]
Hi Guys,

   I am facing issue while compiling documents for watchOS SDK. I have updated the jazzy version to the latest version 0.7.2. Following is the error.

/usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.7.3/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.7.3/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "/Volumes/Development/Projects/Projects/MyFramework/BackupFromiMac/DevelopmentDrive/MyFramework\\ Projects/MyFramework/iOS-Source/MyFramework-sdk-iOS/LibSource/Builds/MyFrameworkSDK/watchOS/MyFramework.framework/Headers/MyFramework.h", "--", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator3.0.sdk", "-I", "/Volumes/Development/Projects/Projects/MyFramework/BackupFromiMac/DevelopmentDrive/MyFramework\\ Projects/MyFramework/iOS-Source/MyFramework-sdk-iOS/LibSource/Builds/MyFrameworkSDK/watchOS/MyFramework.framework"] (RuntimeError)

	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.7.3/lib/jazzy/sourcekitten.rb:147:in `run_sourcekitten'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:65:in `block in build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.7.3/lib/jazzy/doc_builder.rb:63:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jazzy-0.7.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
Command /bin/sh failed with exit code 1

I have added a RunTime script to generate the jazzy documentation, however, I am not able to proceed further due to the error. Please see the script and let me know if any changes has ti be made to the script.

jazzy --objc --clean --framework-root ../Builds/MyFrameworkSDK/watchOS/MyFramework.framework \
--module MyFramework --sdk watchsimulator --output ../Builds/Docs/watchOS \
--umbrella-header ../Builds/MyFrameworkSDK/watchOS/MyFramework.framework/Headers/MyFramework.h \
--skip-undocumented \
--author "MyFramework iOS Development Team.<br><a href=\"https://MyFramework.com/api/watchOS/getting-started.html\">Getting Started Guide</a> | <a target=_new href=\"https://abc.com/support.html\">Support Page</a>"
--author_url "https://abc.com" \
--github_url "https://github.com/MyFramework/watchOSLib" \
--theme fullwidth \
--hide-documentation-coverage \
--documentation "../Markdown/*.md" \
--head "<a target=_new href=https://abc.com><img src=\"https://abc.com/images/abcRGB.svg\" height=\"48\" alt=\"MyFramework\"/></a>"

**Comment by jpsim** [comment]
any chance you can share the project where this is failing with us? Or log the output of the `sourcekitten` invocation here?

**Comment by vnramachandra** [comment]
Sure, I will share the project in a while.

**Comment by vnramachandra** [comment]
[MyFramework.zip](https://github.com/realm/jazzy/files/728676/MyFramework.zip)

Here in the project, we have created aggregate called 'Universal' which builds universal Apple Watch framework and also inserted jazzy code which we are trying to generate documentation for. However, we are still observing the issue. Please have a look at it and let me know if you need any further details.

Thanks,
Ramachandra VN.

**Comment by jpsim** [comment]
This works:

```
jazzy --objc --clean --sdk watchsimulator --umbrella-header MyFramework/MyFramework.h --framework-root .
```
