### ISSUE TITLE
Custom theme path expansion crashes w/Ruby 2.4

### ISSUE THREAD

**Issue by friedbunny** [realm/jazzy#752]
Using a custom theme with jazzy v0.7.4 and Ruby v2.4.x results in a crash [here](https://github.com/realm/jazzy/blob/0e77e46b041295009835788b5e29a88831006f07/lib/jazzy/config.rb#L298):

```
/jazzy/lib/jazzy/config.rb:298:in `block in <class:Config>': unexpected return (LocalJumpError)
    from /jazzy/lib/jazzy/config.rb:36:in `instance_exec'
    from /jazzy/lib/jazzy/config.rb:36:in `set'
    from /jazzy/lib/jazzy/config.rb:55:in `block in attach_to_option_parser'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1552:in `block in parse_in_order'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1538:in `catch'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1538:in `parse_in_order'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1532:in `order!'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1626:in `permute!'
    from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/optparse.rb:1648:in `parse!'
    from /jazzy/lib/jazzy/config.rb:383:in `parse_command_line'
    from /jazzy/lib/jazzy/config.rb:340:in `parse!'
    from /jazzy/bin/jazzy:15:in `<main>'
```

This is because newer versions of Ruby strictly disallow `return` from within a block, such as:

```ruby
parse: ->(t) do
    return expand_path(t) unless t == 'apple' || t == 'fullwidth'
    Pathname(__FILE__).parent + 'themes' + t
end
```

/cc @1ec5

**Comment by 1ec5** [comment]
> newer versions of Ruby strictly disallow return from within a block

Nice, this will avoid issues like #711 in the future.
