### ISSUE TITLE
can't parse compiler arguments from `xcodebuild` output

### ISSUE THREAD

**Issue by 5SMNOONMS5** [realm/jazzy#758]
**Version**
```bash
jazzy-0.7.4
ruby 2.0.0p648
```

**OS**
macOS Sierra

**Description**
This was my original code 
```bash
  --xcodebuild-arguments -project,GCFrameworks.xcodeproj,-scheme,GCFramework-iOS \
```
And then it appeared error message 
```bash
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/xcodebuild-EA9315EB-1812-439A-8DF9-5E20A6D2ECE7.log
Failed to generate documentation
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--", "-project", "GCFrameworks.xcodeproj", "-scheme", "GCFramework-iOS"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/xcodebuild-EA9315EB-1812-439A-8DF9-5E20A6D2ECE7.log

Failed to generate documentation
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/sourcekitten.rb:193:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/lib/jazzy/doc_builder.rb:65:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.4/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```
I fix it by replace my scheme from **GCFramework-iOS** into **GCFrameworkIOS**，because I will have other OS version framework , so have any idea how to let jazzy parse hyphen character in --xcodebuild-arguments

**Comment by jpsim** [comment]
It's not that jazzy isn't parsing hyphens, it's that your scheme name `GCFramework-iOS` differs from your module name `GCFrameworkIOS`. Although that's only an educated guess based on the information you provided.

**Comment by 5SMNOONMS5** [comment]
Thanks for the response 。I used **GCFrameworkIOS** after faced this problem，My original scheme and module all name  **GCFramework-iOS**

**Comment by 5SMNOONMS5** [comment]
@jpsim. lol sorry, it was my mistake, I tried roll back via git and I used underline for the module name.
