### ISSUE TITLE
Build Success but jazzy crashed!!

### ISSUE THREAD

**Issue by yishuiliunian** [realm/jazzy#762]
build with shell

~~~
 jazzy --objc -m QCLOUDCIClientUIDemo --sdk iphone --xcodebuild-arguments --,-workspace,QCLOUDCIClientUIDemo.xcworkspace,-scheme,QCLOUDCIClientUIDemo 
~~~
the ternimal outpu is 

~~~
STONEDONG-MC0 :: QCLOUDCIClientUIProject/Demos/QCLOUDCIClientUIDemo ‹human_check*› % jazzy --objc -m QCLOUDCIClientUIDemo --sdk iphone --xcodebuild-arguments --,-workspace,QCLOUDCIClientUIDemo.xcworkspace,-scheme,QCLOUDCIClientUIDemo                                   1 ↵
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/b8/3t093jf94z94r5ddxpbsghgr0000gn/T/xcodebuild-94CFF4D2-39B9-409C-9A54-B4DDF666B169.log
Failed to generate documentation
/Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/executable.rb:36:in `execute_command': /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--", "-workspace", "QCLOUDCIClientUIDemo.xcworkspace", "-scheme", "QCLOUDCIClientUIDemo"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/b8/3t093jf94z94r5ddxpbsghgr0000gn/T/xcodebuild-94CFF4D2-39B9-409C-9A54-B4DDF666B169.log

Failed to generate documentation
        from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/sourcekitten.rb:216:in `run_sourcekitten'
        from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:67:in `block in build'
        from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `chdir'
        from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `build'
        from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/bin/jazzy:15:in `<top (required)>'
        from /Users/dongzhao/.rvm/rubies/ruby-2.4.0/bin/jazzy:22:in `load'
        from /Users/dongzhao/.rvm/rubies/ruby-2.4.0/bin/jazzy:22:in `<main>'
        from /Users/dongzhao/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/dongzhao/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
~~~

but the log show it is build success

~~~

Validate /Users/dongzhao/Library/Developer/Xcode/DerivedData/QCLOUDCIClientUIDemo-heafgcewqxfhzxcrqncuvtelprqt/Build/Products/Debug-iphoneos/QCLOUDCIClientUIDemo.app
    cd /Users/dongzhao/Works/QCloud/Src/iOS/Git/QCLOUDCIClientUIProject/Demos/QCLOUDCIClientUIDemo
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/dongzhao/.rvm/gems/ruby-2.4.0/bin:/Users/dongzhao/.rvm/gems/ruby-2.4.0@global/bin:/Users/dongzhao/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/dongzhao/.rvm/gems/ruby-2.4.0/bin:/Users/dongzhao/.rvm/gems/ruby-2.4.0@global/bin:/Users/dongzhao/.rvm/rubies/ruby-2.4.0/bin:/opt/local/bin:/Users/dongzhao/bin:/Users/dongzhao/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/Users/dongzhao/bin:/Users/dongzhao/.rvm/bin:/Users/dongzhao/.rvm/bin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/dongzhao/Library/Developer/Xcode/DerivedData/QCLOUDCIClientUIDemo-heafgcewqxfhzxcrqncuvtelprqt/Build/Products/Debug-iphoneos/QCLOUDCIClientUIDemo.app

** BUILD SUCCEEDED **
~~~

**Comment by jpsim** [comment]
That's a very short log. Did you truncate it? Seems you didn't include the part that made jazzy fail 🤔

**Comment by yishuiliunian** [comment]
@jpsim  ， i run it again, and attach the log file. please check it.
~~~
STONEDONG-MC0 :: QCLOUDCIClientUIProject/Demos/QCLOUDCIClientUIDemo ‹human_check*› % jazzy --objc -m QCLOUDCIClientUIDemo --sdk iphone --xcodebuild-arguments --,-workspace,QCLOUDCIClientUIDemo.xcworkspace,-scheme,QCLOUDCIClientUIDemo
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/b8/3t093jf94z94r5ddxpbsghgr0000gn/T/xcodebuild-A67010FC-7412-4E61-99D4-B521B1BD39C6.log
Failed to generate documentation
/Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/executable.rb:36:in `execute_command': /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--", "-workspace", "QCLOUDCIClientUIDemo.xcworkspace", "-scheme", "QCLOUDCIClientUIDemo"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/b8/3t093jf94z94r5ddxpbsghgr0000gn/T/xcodebuild-A67010FC-7412-4E61-99D4-B521B1BD39C6.log

Failed to generate documentation
	from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/sourcekitten.rb:216:in `run_sourcekitten'
	from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `build'
	from /Users/dongzhao/.rvm/gems/ruby-2.4.0@global/gems/jazzy-0.7.5/bin/jazzy:15:in `<top (required)>'
	from /Users/dongzhao/.rvm/rubies/ruby-2.4.0/bin/jazzy:22:in `load'
	from /Users/dongzhao/.rvm/rubies/ruby-2.4.0/bin/jazzy:22:in `<main>'
	from /Users/dongzhao/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dongzhao/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
~~~
[xcodebuild-A67010FC-7412-4E61-99D4-B521B1BD39C6.txt](https://github.com/realm/jazzy/files/881773/xcodebuild-A67010FC-7412-4E61-99D4-B521B1BD39C6.txt)

**Comment by johnfairh** [comment]
If you are still stuck on this:

The jazzy command needs more parameters: if you use --xcodebuild-arguments then you have to give it all the objc compiler parameters to pass on.

Do you really need to set workspace & scheme?  If not then the command is something like `jazzy --objc -m QCLOUDCIClientUIDemo --umbrella-header (PATH) --framework-root .`

The long command to pass workspace + scheme is something like:
`jazzy --objc -m ... --xcodebuild-arguments --objc,(YOUR UMBRELLA HEADER),--,-x,objective-c,-isysroot,(PATH TO SDK),-I,(INCLUDE DIRECTORY),-workspace,...,-scheme,...`

**Comment by edburns** [comment]
I am seeing a similar problem.  I see this output when running jazzy:

```
jazzy --module occ --include Sources/occ/Session.swift 
Running xcodebuild
Could not parse compiler arguments from `xcodebuild` output.
Please confirm that `xcodebuild` is building a Swift module.
Saved `xcodebuild` log file: /var/folders/qx/5d47k94x31d9d256lh86kllr00gk8f/T/xcodebuild-04B22C31-F721-4E14-8CAB-74135B260989.log
Failed to generate documentation
Traceback (most recent call last):
	7: from /usr/local/bin/jazzy:23:in `<main>'
	6: from /usr/local/bin/jazzy:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/bin/jazzy:15:in `<top (required)>'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `build'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:64:in `chdir'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/doc_builder.rb:66:in `block in build'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/sourcekitten.rb:230:in `run_sourcekitten'
/usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/lib/ruby/gems/2.5.0/gems/jazzy-0.9.3/bin/sourcekitten ["doc", "--module-name", "occ", "--"] (RuntimeError)

Running xcodebuild

Could not parse compiler arguments from `xcodebuild` output.

Please confirm that `xcodebuild` is building a Swift module.

Saved `xcodebuild` log file: /var/folders/qx/5d47k94x31d9d256lh86kllr00gk8f/T/xcodebuild-04B22C31-F721-4E14-8CAB-74135B260989.log

Failed to generate documentation
```
However, the build output ends with

```

** BUILD SUCCEEDED **

```

So the xcodebuild appears to have worked.

**Comment by johnfairh** [comment]
Closing this, inactive.
