### ISSUE TITLE
Occur an error while generating doc with .jazzy.yaml

### ISSUE THREAD

**Issue by MESIRD** [realm/jazzy#764]
I want to generate an Objective-C document for my personal project, but I get an error everytime when I run `jazzy` command.
I use the .jazzy.yaml sample of Realm(ObjC), and make some changes on it.
mine looks like below:
```
jazzy \
  --objc \
  --clean \
  --output docs/objc_output
```
in the root dir of my `MyJazzyProject` project, I run `jazzy`, and this is what I get.
```
Using config file /Users/mesird/Desktop/MyJazzyProject/.jazzy.yaml
/Users/mesird/Software/ruby/gems/jazzy-0.7.5/lib/jazzy/config.rb:402:in `parse_config_file': undefined method `each' for "jazzy \\ --objc \\ --clean \\ --output docs/objc_output":String (NoMethodError)
	from /Users/mesird/Software/ruby/gems/jazzy-0.7.5/lib/jazzy/config.rb:344:in `parse!'
	from /Users/mesird/Software/ruby/gems/jazzy-0.7.5/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
```

**Comment by jpsim** [comment]
The `.jazzy.yaml` file shouldn't be the jazzy command to run, but rather a YAML representation of jazzy's configuration options. Please replace the contents of the file with:

```yaml
objc: true
clean: true
output: docs/objc_output
```

and run `jazzy` again.

**Comment by MESIRD** [comment]
@jpsim 
Thank you for your reply, I've revised the .jazzy.yaml as you said above, and now I encounter a new issue, which is the same problem as #760 .

I've followed your suggestion to run `jazzy` after executing
```
$ export SOURCEKIT_LOGGING=3
```
but it is still the same error.

```
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.5/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.5/lib/jazzy/SourceKitten/bin/sourcekitten ["doc", "--objc", "''", "--", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk", "-I", "''"] (RuntimeError)

	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.5/lib/jazzy/sourcekitten.rb:216:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.7.5/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
```

**Comment by jpsim** [comment]
How about running this?

```
$ export SOURCEKIT_LOGGING=3
$ sourcekitten doc --objc '' -- -x objective-c -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I ''
```

**Comment by MESIRD** [comment]
@jpsim 
The output is:

```
MESIRDMAC:MyJazzyProject mesird$ export SOURCEKIT_LOGGING=3
MESIRDMAC:MyJazzyProject mesird$ sourcekitten doc --objc '' -- -x objective-c -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I ''
Illegal instruction: 4
```

**Comment by jpsim** [comment]
All SourceKitten is doing is forwarding those arguments to libclang, and libclang is crashing. You should send the arguments that libclang needs to parse your headers.

**Comment by MESIRD** [comment]
@jpsim 
Thank you so much, and finally I make it.
This is my config file: 

```
objc: true
clean: true
output: docs/objc_output
umbrella_header: MyJazzyProject/MyJazzy.h
framework_root: .
sdk: macosx
```
