### ISSUE TITLE
jazzy command fails: sourcekitten looking for Swift 3.0.2 instead of 3.1

### ISSUE THREAD

**Issue by Mozahler** [realm/jazzy#793]
/Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/sourcekitten.rb:209:in `run_sourcekitten': Unable to find an Xcode with swift version 3.0.2. (RuntimeError)
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:67:in `block in build'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `chdir'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/lib/jazzy/doc_builder.rb:65:in `build'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/gems/jazzy-0.7.5/bin/jazzy:15:in `<top (required)>'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/jazzy:22:in `load'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/jazzy:22:in `<main>'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Alex/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'

sourcekitten version
0.17.0
I tried to reinstall sourcekitten via home-brew, but got:
Error: sourcekitten-0.17.0 already installed 
(should I ask this question here, in sourcekitten issues, or on StackOverflow?) I don't want to spam.

**Comment by Mozahler** [comment]
Sorry. I didn't specify the swift version in my yaml file.
