### ISSUE TITLE
jazzy - environment ruby error

### ISSUE THREAD

**Issue by erenkabakci** [realm/jazzy#807]
After following very straightforward installation steps, unfortunately `jazzy` is not working out of the box.

I have read all the documentation I could find and checked directories etc. I get the following error after running `jazzy`

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate activesupport-4.2.7.1, because json-2.1.0 conflicts with json (>= 1.7.7, ~> 1.7) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy/source_declaration/type.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy/source_declaration.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy/doc_builder.rb:16:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/lib/jazzy.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.8.1/bin/jazzy:13:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

**Comment by erenkabakci** [comment]
Looks like I had different versions of json installed `json (2.1.0, 1.7.7)`

Removing `2.1.0` worked for me, you might not want to uninstall other versions depending on your needs.

**Comment by josmanperez** [comment]
Hello @erenkabakci , may I ask you how do you remove json 2.1.0? or @johnfairh how do you upgrade activesupport to 4.2.8?

Thank you so much

**Comment by erenkabakci** [comment]
@josmanperez It has been a very long time since but I guess they are just normal ruby gems. You can follow any step on the almighty internet. https://stackoverflow.com/questions/42577346/uninstalling-ruby-gems
