### ISSUE TITLE
Undefined method `empty?' for 3.1:Float (NoMethodError)

### ISSUE THREAD

**Issue by nvzqz** [realm/jazzy#860]
I'm trying to generate docs for [RandomKit](https://github.com/nvzqz/RandomKit/) and I get this error:

```
$ jazzy --source-directory ../RandomKit --config .jazzy.yaml

Using config file /Users/nvzqz/dev/projects/swift/RandomKit.gh-pages/.jazzy.yaml
/usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:165:in `block in <class:Config>': undefined method `empty?' for 3.1:Float (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:36:in `instance_exec'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:36:in `set'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:45:in `set_if_unconfigured'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:421:in `block in parse_config_file'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:409:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:409:in `parse_config_file'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/lib/jazzy/config.rb:351:in `parse!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jazzy-0.8.3/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

Here's my Ruby version:

```
$ ruby --version

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
```

Thanks!

**Comment by johnfairh** [comment]
Looks like setting `swift_version` in the config file does not work any more, whether or not the version has a dot in it.  Not a ruby version issue.

It does works from the command-line (`--swift-version`) so I hope that will do for a workaround.

**Comment by segiddins** [comment]
I think it needs to be a string rather than a number, try quoting it?

**Comment by nvzqz** [comment]
@segiddins quoting it worked. It worked for me previously without quoting it. Something might've changed since then. The last time I generated the docs was June 1st.
