### ISSUE TITLE
Podfile details about the version of a dependency to be used not used by jazzy. 

### ISSUE THREAD

**Issue by dirtyhenry** [realm/jazzy#920]
When running jazzy for a pod repo, the pod resolution fails with the following error: 

``` 
Using config file /Users/mick/Developer/Projects/Flaneur/Code/FlaneurOpen/.jazzy.yaml
Analyzing dependencies
Fetching podspec for `FlaneurOpen` from `/Users/mick/Developer/Projects/Flaneur/Code/FlaneurOpen`
/Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/resolver.rb:461:in `handle_resolver_error': [!] Unable to satisfy the following requirements: (Pod::Informative)

- `Kingfisher (~> 4.0)` required by `FlaneurOpen (0.5.1-alpha)`
- `Kingfisher (~> 3.10)` required by `FlaneurImagePicker (0.1.0)`
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/resolver.rb:80:in `rescue in resolve'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/resolver.rb:72:in `resolve'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:771:in `block in resolve_dependencies'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:768:in `resolve_dependencies'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/installer/analyzer.rb:79:in `analyze'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:242:in `analyze'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/user_interface.rb:64:in `section'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:116:in `install!'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/jazzy-0.9.0/lib/jazzy/podspec_documenter.rb:22:in `block in sourcekitten_output'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.3.1/lib/cocoapods/config.rb:41:in `with_changes'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/jazzy-0.9.0/lib/jazzy/podspec_documenter.rb:18:in `sourcekitten_output'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:62:in `build'
	from /Users/mick/.rvm/gems/ruby-2.3.1/gems/jazzy-0.9.0/bin/jazzy:15:in `<top (required)>'
	from /Users/mick/.rvm/gems/ruby-2.3.1/bin/jazzy:23:in `load'
	from /Users/mick/.rvm/gems/ruby-2.3.1/bin/jazzy:23:in `<main>'
	from /Users/mick/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mick/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

The code source giving this result is available here: https://github.com/FlaneurApp/FlaneurOpen/tree/129b57f618d4671c8840e0f61e7d13716a1c9570

I think the problem is that the `Podfile` is giving information about what version `FlaneurImagePicker` should be used (ie git URL and branch name), but it seems to be ignored by the pod resolution. `pod install`, however, works just fine.

The project is using jazzy 0.9.0 with Swift 4.0 code.

**Comment by segiddins** [comment]
It only uses your podspec, not the podfile.

**Comment by johnfairh** [comment]
Right.  So `pod lib lint` will say the same thing.

#650 is similar.  I think a common solution might be to let the user give some arbitrary lines for inclusion in the 'target' part of the podfile that jazzy generates under the covers.

**Comment by dirtyhenry** [comment]
Fair enough. This being said, I remember seeing an issue somewhere where people from Cocoapods considered the `podspec` to specify what pods had to be used, and the `Podfile` to speficy where to find them.

For other people visiting this issue: I met it at development time. After publishing my `FlaneurImagePicker` dependency to the public cocoapods repository, it used the public version instead of the branch version I wanted to but overall, jazzy ended up working fine. (which explains why the code version i mentioned in the body now works fine too)
