### ISSUE TITLE
Argument list too long - sourcekitten (Errno::E2BIG)

### ISSUE THREAD

**Issue by ptso** [realm/jazzy#924]
**Environment Details**
macOS 10.12.6
Jazzy 0.9.0
Xcode 8.3.3 (8E3004b)

**Configuration File**
```
module: PeterTool
author: Peter
author_url: https://peter.xxx
clean: true
objc: true
framework_root: ../
umbrella_header: PeterToolUmbrella.h
output: docs/
documentation: guides_build/*.md

docset_icon: ../PeterTool/Images.xcassets/AppIcon.appiconset/PeterTool.png
docset_path: ../docset/


copyright: '© 2017 [Peter](https://peter.xxx/).'
```

**Output**
```
Using config file /Users/peter/PeterTool/docs/.jazzy.yaml
/Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:49:in `exec': Argument list too long - /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/bin/sourcekitten (Errno::E2BIG)
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:49:in `block in popen4ext'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:85:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:85:in `block in do_popen'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:62:in `fork'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:62:in `do_popen'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:46:in `popen4ext'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:336:in `block (2 levels) in spawn'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:335:in `block in spawn'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:374:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:374:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/open4-1.3.4/lib/open4.rb:334:in `spawn'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/executable.rb:31:in `execute_command'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/sourcekitten.rb:221:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```
I used Objective-C  for my project.
I think it might be related to sourcekitten but I don't know how to figure it out.
Could anyone teach me how to fix it? 
Thanks a lot
Peter

**Comment by johnfairh** [comment]
This is probably the code in jazzy that adds 'include' params for every subdirectory under `framework_root` -- this is usually too aggressive but harmless.

Is there anything you can delete from that directory (eg. an existing jazzy output docs tree)?  If not then I think will have to go down the manual xcodebuild arguments route instead of setting framework_root + umbrella_header.

Real fix might be to include only the directories with .h files in them [or figure out how to auto-build objc projects..]

**Comment by ptso** [comment]
Thanks John.
However, I tried to put those files into one folder and used jazzy to generate the document, but it still failed.
It showed "Loading libclang.dylib failed:...". Would you please teach me how to figure it out? 
Thanks.
Peter
```
Using config file /Users/peter/Test/.jazzy.yaml
fatal error: Loading libclang.dylib failed: file /Users/jsimard/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 61
/Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/executable.rb:36:in `execute_command': /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/bin/sourcekitten ["doc", "--objc", "/Users/peter/Test/PeterUmbrella.h", "--", "-x", "objective-c", "-isysroot", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk", "-I", "/Users/peter/Test", "-fmodules"] (RuntimeError)

fatal error: Loading libclang.dylib failed: file /Users/jsimard/Projects/jazzy/SourceKitten/Source/SourceKittenFramework/library_wrapper.swift, line 61
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/sourcekitten.rb:221:in `run_sourcekitten'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `build'
	from /Library/Ruby/Gems/2.0.0/gems/jazzy-0.9.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:23:in `load'
	from /usr/local/bin/jazzy:23:in `<main>'
```

**Comment by johnfairh** [comment]
Not seen that before.  It means sourcekitten cannot find libclang.dylib using [these rules](https://github.com/jpsim/SourceKitten#how-is-sourcekit-resolved).

It might be related to how `xcrun --show-sdk-path` has given a `/Library/Developer/CommandLineTools` path in your pasted output above instead of something involving Xcode - I think that's an unusual system config.

**Comment by ptso** [comment]
I removed the .app file in the folder and used other laptop to try, this issue disappeared. Thanks John.

**Comment by virl** [comment]
Please fix, issue still exists even in simplest configurations for Jazzy, especially if there are Carthage folders with checkouts present.
