### ISSUE TITLE
Objective-C protocol causes failure on watchOS only

### ISSUE THREAD

**Issue by sjmerel** [realm/jazzy#931]
given this simple header file umbrella.h:

```
@protocol MyProtocol
@end
```

This invocation works:
jazzy --objc --umbrella-header ./umbrella.h --output out --sdk iphonesimulator

But this one fails:
jazzy --objc --umbrella-header ./umbrella.h --output out --sdk watchsimulator

The error:

````
/usr/local/Cellar/ruby/2.4.3_1/lib/ruby/gems/2.4.0/gems/jazzy-0.9.0/lib/jazzy/executable.rb:36:in `execute_command': /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/gems/2.4.0/gems/jazzy-0.9.0/bin/sourcekitten ["doc", "--objc", "/Users/steve/work/fm/tmp/umbrella.h", "--", "-x", "objective-c", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator4.2.sdk", "-I", "''", "-fmodules"] (RuntimeError)

	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/gems/2.4.0/gems/jazzy-0.9.0/lib/jazzy/sourcekitten.rb:221:in `run_sourcekitten'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/gems/2.4.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:66:in `block in build'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/gems/2.4.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `chdir'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/gems/2.4.0/gems/jazzy-0.9.0/lib/jazzy/doc_builder.rb:64:in `build'
	from /usr/local/Cellar/ruby/2.4.3_1/lib/ruby/gems/2.4.0/gems/jazzy-0.9.0/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
````

**Comment by johnfairh** [comment]
I confirm this on 0.9.0 but not on master, which works OK.  This looks to be a problem with the Xcode 9+ watch[simulator] SDKs and the sourcekitten version (0.18.2) that ships with jazzy 0.9.0 hitting a nil force-unwrap calling SourceKit.  So, this will be fixed in the next release.  As a workaround until then you could run jazzy from source.

**Comment by jpsim** [comment]
I'll cut a release today.

**Comment by jpsim** [comment]
https://github.com/realm/jazzy/releases/tag/v0.9.1
