### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by allanmacatingrao** [realm/jazzy#940]
```
/Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/sourcekitten.rb:68:in `block in group_custom_categories': undefined method `flat_map' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/sourcekitten.rb:67:in `map'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/sourcekitten.rb:67:in `group_custom_categories'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/sourcekitten.rb:59:in `group_docs'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/sourcekitten.rb:680:in `parse'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:145:in `build_docs_for_sourcekitten_output'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/lib/jazzy/doc_builder.rb:77:in `build'
	from /Library/Ruby/Gems/2.3.0/gems/jazzy-0.9.1/bin/jazzy:15:in `<top (required)>'
	from /usr/local/bin/jazzy:22:in `load'
	from /usr/local/bin/jazzy:22:in `<main>'
```

**Comment by johnfairh** [comment]
I think this means the yaml file has the wrong format, something amiss with the `children` entry that should be child of each entry in the `custom_categories` node -- [example of a working yaml config file](https://github.com/bustoutsolutions/siesta/blob/1665db77a35b0e5c60269825d2e9b4d6971b81b5/.jazzy.yaml).  If that doesn't help then maybe share the config file?

**Comment by allanmacatingrao** [comment]
Thant was the case. thank you.
